ckanext/ontario_theme/fanstatic/ontario_theme.css, ckanext/ontario_theme/fanstatic/ontario_theme.less
Theme was overriding paragraph font size leading to inconsistent sizing between paragraphs and lists. Removed override. We can adjust font size globally in the future, if we want to.
=> Bug: Mismatched p and li font sizes

ckanext/ontario_theme/templates/header.html
Remove as per user testing findings and for current
html5 shim error in CKAN (already patched for next release).
=> Task: Remove stats menu item.

ckanext/ontario_theme/templates/snippets/search_form.html
Rework logic to avoid calling `remove_field()`
when it doesn't exist.
Trying to access the `remove_field()` function
when displaying search results for organizations
and groups caused a missing attribute error. This
does not exist in the controller and facets are not setup
for these models in the templates.
References:
- [groups.index](https://github.com/ckan/ckan/blob/717811526bfb25e2af16ae916e6d0d2a76da7c9a/ckan/controllers/group.py#L140)
- [package.search](https://github.com/ckan/ckan/blob/717811526bfb25e2af16ae916e6d0d2a76da7c9a/ckan/controllers/package.py#L134) 
- [package.search.html](https://github.com/ckan/ckan/blob/717811526bfb25e2af16ae916e6d0d2a76da7c9a/ckan/templates/package/search.html#L21)
- [group.index.html](https://github.com/ckan/ckan/blob/2.8/ckan/templates/group/index.h …
=> Bug: Missing attribute error on query.

ckanext/ontario_theme/templates/package/read_base.html
We are not currently using groups and have hidden them elsewhere from users that are not logged in. For the time being hide groups from dataset page tab list.
=> Remove group

ckanext/ontario_theme/templates/package/snippets/resource_item.html
Display resource size if available.
Currently the resource sub-page is handled by scheming and that's implemented separately for now in it's own extension.
=> Resource size

ckanext/ontario_theme/templates/package/base_form_page.html, ckanext/ontario_theme/templates/package/edit_base.html, ckanext/ontario_theme/templates/package/new_resource.html, ckanext/ontario_theme/templates/package/new_resource_not_draft.html, ckanext/ontario_theme/templates/package/resource_edit_base.html, ckanext/ontario_theme/templates/package/snippets/disclaimer.html
A reminder note has been added in left sidebar when user adds or edits a resource or dataset.
For instance, some things shouldn't be added / shared such as personal information.
=> Add data disclaimer

ckanext/ontario_theme/templates/snippets/package_item.html
Users were assuming all datasets have data (resources). This PR adds a distinction on the dataset search results page to help indicate what has a resource and what doesn't.
"Resource formats" wording aligns with canadian federal data catalogue. "This dataset has no data" wording comes from dataset template when a dataset does not have a resource.
=> Distinguish datasets with resource

ckanext/ontario_theme/templates/package/snippets/resource_item.html
Small change to resource menu under "explore" to change:
- "go to resource" to "open"
- "more information" to "about"
Addresses the following ticket: https://trello.com/c/8lJKv19T/354-people-dont-know-what-more-information-and-go-to-resource-will-do
This was done to address confusion in initial usability studies. More common language is proposed.
=> Resource menu change

ckanext/ontario_theme/fanstatic/ontario_theme.css, ckanext/ontario_theme/fanstatic/ontario_theme.less, ckanext/ontario_theme/templates/header.html, ckanext/ontario_theme/templates/package/read_base.html, ckanext/ontario_theme/templates/package/snippets/package_form.html, ckanext/ontario_theme/templates/user/dashboard.html
This consists of a few small cosmetic changes to Colby as a result of confusion in initial user testing. These changes include:
- having user datasets (and not news feed) as the default view for the user dashboard
- harmonizing the look of the search bar in the datasets search page with the left side filtering options (matching with the grey of the left side filtering options)
- Change the "Manage" button for datasets to the more commonly used "Edit" and apply colour so it doesn't blend in so much with the background
- change the "next: add data" to "save and add data" in the "new datasets" page to make it clear that your meta data entered so far will be saved
=> Ui adjustments

ckanext/ontario_theme/templates/package/snippets/resource_item.html
This stems from a request from a current Colby user to hide "(unknown size)" next to resources that are links and therefore wouldn't have a filesize anyways. While this solution hides all resources that have no filesize (not just resources that are links), it effectively solves the issue.
=> Improvement: remove '(unknown size)' from resources

ckanext/ontario_theme/templates/package/read_base.html
This has one simple change: restoring the link to groups for a package in the show package page. It was originally removed because we weren't using groups, but they've been proven to be quite useful.
=> Improvement: Restored groups link in the show package page

ckanext/ontario_theme/templates/organization/snippets/helper.html
The link to og leads in the organizations index page was broken because we're not using sharepoint anymore. The link was updated to the new og leads colby dataset.
=> Bug: OG staff leads link doesn't work anymore

ckanext/ontario_theme/templates/header.html
This pull request has one major change to address:
https://trello.com/c/yoZPZRE8/388-language-selector-missing-from-site
A EN/FR toggle was added to the header.
=> Improvement: Language toggle link added in header for english and french

ckanext/ontario_theme/templates/header.html, ckanext/ontario_theme/templates/snippets/ontario_theme_language_selector.html
The header_account_logged block was added a few months
ago to change the user dashboard link to go to the users
datastes instead of activity feed. This added a block outside
of its parent block(s) where it we were already calling super().
Language selector did not appear in the non-authed user header.
While adding this I also moved it to a snippet.
=> Task: Cleanup header template and lang toggle.

ckanext/ontario_theme/fanstatic/ontario_theme.css, ckanext/ontario_theme/fanstatic/ontario_theme.less, ckanext/ontario_theme/templates/organization/index.html, ckanext/ontario_theme/templates/snippets/add_dataset.html
This pull request consists of one commit to address:
https://trello.com/c/QN1a5T9f/385-harmonizing-the-look-of-the-search-bar-in-the-datasets-search-page-with-the-left-side-filtering-options-matching-with-the-grey-o
It changes the organizations search bar to match the packages search bar.
=> Harmonize search bar look

ckanext/ontario_theme/templates/package/resource_read.html
This pull request has one change to address:
https://trello.com/c/VslFl3IJ/396-look-at-changing-all-instances-go-to-resource-to-open-to-be-consistent-with-pr-35
Any instance of "go to resource" across the codebase was changed to "open".
=> Change go to resource to open globally

ckanext/ontario_theme/templates/package/snippets/resource_item.html
This is due to using ckan master template as the base
instead of the ckan version we're using (2.8.2). Some
routes are using flask and others are using pylons and
each version more flask views are introduced that replace
the old controllers but this breaks if the migration hasn't
happened yet for a controller.
Introduced in PR #35
=> Bug: Resource item edit link gave 404.

ckanext/ontario_theme/templates/datapusher/resource_data.html
Error message was giving much more detailed information than
needed to the user. This prevents divulging unnecessary information
in the web UI.
=> Improvement: Datapusher template override for user friendly error message.

ckanext/ontario_theme/templates/home/snippets/ontario_theme_contact_us.html, ckanext/ontario_theme/templates/home/snippets/ontario_theme_featured_content.html, ckanext/ontario_theme/templates/home/snippets/ontario_theme_intro.html
This pull request consists of html structure changes for the landing page for the public-facing data catalogue:
- the conversion of the 3 columns under the main search banner to one column
- featured datasets cards changed to remove images
- contact us section changed from two columns and multiple rows to one column/row
=> Odc beta layout

ckanext/ontario_theme/fanstatic/colours.less, ckanext/ontario_theme/fanstatic/ontario_theme.css, ckanext/ontario_theme/fanstatic/ontario_theme.less
This PR consists of one change, changing the general anchor hover, visited, and focus colours to match ontario.ca. These colours are stored in the colours.less file.
=> Task: Update visited and hover styles to match ontario.ca.

ckanext/ontario_theme/templates/header.html
For now, just removing this link from UI to help avoid as many
people thinking they need to or are able to login.
=> Task: Remove login link from UI.

ckanext/ontario_theme/plugin.py, ckanext/ontario_theme/templates/group/read.html, ckanext/ontario_theme/templates/home/snippets/search.html, ckanext/ontario_theme/templates/organization/read.html, ckanext/ontario_theme/templates/package/search.html, ckanext/ontario_theme/templates/scheming/display_snippets/fluent_tags.html, ckanext/ontario_theme/templates/snippets/ontario_theme_keywords_facet.html, ckanext/ontario_theme/tests/test_helpers.py, config/solr/schema.xml
Fluent doesn't support multi-lingual tag support out of the box.
Keywords are used in their place as per the fluent readme.
The default behaviour in fluent adds mutli-lingual keywords in forms
and helps display them properly when toggling languages but when adding
them as facets extra work is needed (fluent basically offers multi-lingual
read and write abilities for tags but nothing for search).
Changes include:
- Adding new keywords as facets
- Refactor *_facet() functions in plugin.py
- Index new facets
- Add and update various templates to get new keywords to appear properly throughout
- Add custom helper to get top keywords by language and display on homepage
- New helper tests
- New custom solr schema to add multiValued keyword support
=> Task: Add Multi-lingual tag support

ckanext/ontario_theme/templates/organization/index.html, ckanext/ontario_theme/templates/package/search.html, ckanext/ontario_theme/templates/page.html
**Expected Behaviour:** The user can click into the search input fields on the dataset (package) and organization main pages where the search input is full width.
**Actual Behaviour:** The first quarter of the search input field is not clickable. The `wrapper` class that is used to create a 2 column layout has a `::before` selector that stretches to the top of the wrapper preventing a user from clicking on anything visible but underneath it (e.g. the search field and the filters that may be applied to the search results).
**Fix:** Create a custom block in the `page.html` template that we can use in templates extending it. Then "lift" the search form into this block. This only applies to the organization and dataset (package) search pages. Full width search hasn't been applied to the …
=> Bug: Let user click first quarter of search form.

ckanext/ontario_theme/fanstatic/ontario_theme.css, ckanext/ontario_theme/fanstatic/ontario_theme.less, ckanext/ontario_theme/ontario_theme_dataset.json, ckanext/ontario_theme/templates/package/snippets/resource_item.html, ckanext/ontario_theme/templates/scheming/package/resource_read.html
**Overview:**
- Prevent resource description from overlapping buttons on package page
- Get resource description to show up on package page
- Get bi-lingual resource description to show up on resource page
**Details:** 
Make resource description (ckan core field) multi-lingual in schema.
This currently adds description-en, description-fr instead of _translated.
This was causing the description to not appear in the resource_item.html
because it was not being saved in description_translated or description field.
It was only being saved in description-en and description-fr oddly.
Restructure styles and resource_item.html to display resource details on
a package page in 2 columns. This fixes the description and button
overlap issue.
Override resource_item.html to make the resource display 2 …
=> Improvement: Fix resource description overlap and display.

ckanext/ontario_theme/ontario_theme_dataset.json
This PR consists of 5 commits and focuses on schema changes for the public catalogue based on the first round of feedback on our pilot schema:
- removing the following fields from the schema because they are specific to colby (and will never be populated on the public catalogue):
- program id
- cluster application id
- licence range start
- licence range end
- changing licence_id field name back to original license_id in order to not break core ckan
- adding a "french and english" option to resource language field
=> Odc beta schema updates

ckanext/ontario_theme/fanstatic/labels.less, ckanext/ontario_theme/fanstatic/ontario_theme.css, ckanext/ontario_theme/templates/scheming/package/read.html, ckanext/ontario_theme/templates/scheming/package/snippets/additional_info.html
This PR consists of 1 commit and 1 change. The dataset status snippet from the current catalogue was implement in the new catalogue to pull access_level, exemption, exemption_rationale, and opened_data from the additional_info html snippet and display it in the read html snippet.
=> Task: Implement dataset status snippet

ckanext/ontario_theme/fanstatic/alerts.less, ckanext/ontario_theme/fanstatic/labels.less, ckanext/ontario_theme/fanstatic/ontario_theme.css, ckanext/ontario_theme/fanstatic/ontario_theme.less, ckanext/ontario_theme/templates/package/resource_read.html, ckanext/ontario_theme/templates/package/snippets/ontario_theme_language_disclaimer.html
This PR consists of 3 commits to make 1 change: the addition of a language disclaimer on the resource page that displays in 4 cases:
- you're viewing the site in french and looking at an english only resource. there are french resources available.
- you're viewing the site in french and looking at an english only resource. there are no french resources available.
- you're viewing the site in english and looking at a french only resource. there are english resources available.
- you're viewing the site in english and looking at a french only resource. there are no english resources available.
=> Odc beta add language disclaimer

ckanext/ontario_theme/templates/snippets/ontario_theme_language_selector.html
Originally the toggle used "en" and "fr" for labels. But Ontario.ca uses "english" and "français". This pull request consists of one commit to change those labels.
=> Task: Switch language toggle from EN/FR to english/français

ckanext/ontario_theme/templates/home/snippets/ontario_theme_intro.html
This PR consists of one change and one commit, just fixing the bug in the url for the 'tell us what you think' link on the homepage.
=> Bug: Fix the 'tell us what you think' link on homepage

ckanext/ontario_theme/templates/snippets/package_item.html
This PR consists of four commits to change the title and description in the package_list snippet so that they can display french.
Note: It might be appropriate to fork ckanext-fluent and make a PR to fix it in that extension.
=> Odc beta french package list

ckanext/ontario_theme/ontario_theme_dataset.json
This PR consists of changes to:
- remove "_translated" from non-core fields in the schema
- add "_translated" to core fields in the schema
- use "preset" instead of referring to form_snippet and display_snippet 
Note: Further PRs must change use of get_translated to scheming_language_text (or similar) to resolve this issue.
=> Bug: fluent notation mis-applied.

ckanext/ontario_theme/ontario_theme_dataset.json
Since it's not required anymore, let it be empty.
=> Bug: Add missing validator for email.

ckanext/ontario_theme/templates/home/help.html
Specific dataset atom feed given in the documentation doesn't work. This was replaced with the custom.atom feed and passing the name.
=> Specific dataset atom feed doesn't work.

ckanext/ontario_theme/i18n/ckanext-ontario_theme.pot, ckanext/ontario_theme/i18n/fr/LC_MESSAGES/ckanext-ontario_theme.po, ckanext/ontario_theme/templates/scheming/package/resource_read.html
This PR consists of 8 commits for the following translation fixes:
- Missing translations for 
- access level content
- 'covers', 'contact', 'popular keywords', 'supporting files', 'open', and 'no date range'
- language disclaimers. 
- 'Source' line on resource read page doesn't translate. …
- 'Powered by' (broken by the addition of a <abbr>
=> Odc beta missing fr translations

ckanext/ontario_theme/templates/package/snippets/resources_list.html
This PR consists of 1 commit to fix one bug:
Using data_range_start to sort in the resources_list template breaks all datasets that have a dataset of type 'data' but lack a data_range_start on all of the resources. Moreover, resources should be grouped by the data_range_start and data_range_end combo, not just data_range_start. a new data_range is created with defaults, so that all data type resources have a data_range. Then it is safe to group and sort by data_range.
=> Bug: Accessing non-existent data_range_start breaks everything.

ckanext/ontario_theme/templates/package/snippets/ontario_theme_access_level.html
The access level snippet was simplified to generate the po translations but then not committed.
=> Bug: Missing changes to access level snippet.

ckanext/ontario_theme/templates/group/snippets/info.html, ckanext/ontario_theme/templates/package/read_base.html, ckanext/ontario_theme/templates/snippets/organization.html
This PR consists of 6 commits to make 3 changes:
* remove followers feature from
* group page (read)
* organization page (read)
* package page (read)
This is because the followers feature is only available to users that are logged in, but user accounts will be used only to maintain the catalogue, not to view it.
=> Odc beta remove follow feature

ckanext/ontario_theme/templates/header.html
Originally, groups were providing no function in Colby, but there is intent to use them in Colby and the public catalogue, so it's being readded.
=> Task: Re-add groups link to main menu.

ckanext/ontario_theme/templates/organization/read_base.html, ckanext/ontario_theme/templates/package/base.html, ckanext/ontario_theme/templates/package/resource_read.html, ckanext/ontario_theme/templates/package/snippets/resource_item.html
This PR consists of 2 commits to make the following changes:
* create a ministry-name id and attribute to use for analytics and roll up stats per ministry
* add a class to download and open buttons, resource url, and 'download as [format]' links in order to be able to roll up all resource downloads in analytics
* create a ministry-name id and attribute to dataset and resource pages so stats can be rolled up by dataset
=> Task: Analytics css selectors

ckanext/ontario_theme/ontario_theme_dataset.json, ckanext/ontario_theme/templates/scheming/form_snippets/help_text.html
This PR includes one commit to make two changes:
* add a link to the open data guidebook
* enable markdown and html for help text in the form so that the link can be opened in a new window 
In order to provide more guidance in the add dataset form, for the exemption field a link to the open data guidebook was added. In order to enable this so that the link could be opened in a new window (since the link is in a form), allow_html is enabled for help text.
=> Task: Add link to Open Data Guidebook for exemption field.

ckanext/ontario_theme/templates/scheming/package/read.html
This PR consists of one commit to make one change:
* Short description isn't a field anymore. The snippet specific to displaying the short description was removed.
=> Task: Remove short description snippet from ui.

ckanext/ontario_theme/fanstatic/ontario_theme.css, ckanext/ontario_theme/fanstatic/ontario_theme.less
This PR consists of one commit to fix one bug.
Table styles were changed globally, but they should only affect tables in the section with the class 'additional-info'.
=> Bug: limit table styles to additional-info.

ckanext/ontario_theme/ontario_theme_dataset.json
This PR consists of one commit to make one change:
* Remove 'to be opened' option from new/edit dataset form.
There will be a complementary commit on odc-beta to remove the UI elements.
=> Task: Remove 'to be opened' option from form.

ckanext/ontario_theme/templates/package/snippets/ontario_theme_access_level.html
This PR consists of one commit to make one change:
* remove the 'to be opened' panel from the dataset page. 
This PR should be applied after the option is removed from the form (PR #123 ) has been applied and after any datasets with a 'to be opened' access level have been converted to 'under review'.
=> Remove 'to be opened' panel from UI

ckanext/ontario_theme/fanstatic/ontario_theme.css, ckanext/ontario_theme/fanstatic/ontario_theme.less, ckanext/ontario_theme/templates/package/read_base.html, ckanext/ontario_theme/templates/snippets/organization.html
This PR consists of two changes:
* adding a RSS subscription button to each package page
* adding a RSS subscription button to each organization page
This is so that users of the site don't need necessarily go to the help page to find out about RSS subscriptions and so they have a one-click option.
=> Add RSS subscription buttons

ckanext/ontario_theme/templates/package/snippets/ontario_theme_language_disclaimer.html
This PR consists of one commit to make one change. The language disclaimer display was based on english resources, but it should count the number of the resources of the current site language and the number of bilingual resources.
=> Bug: Language disclaimer display based on number of English resources,

ckanext/ontario_theme/templates/package/snippets/disclaimer.html
The new dataset disclaimer wasn't relevant to the public catalogue.
This PR consists of 1 commit to change the disclaimer to be public catalogue-specific.
Note: when more guidance is available, it can be added.
=> Change new dataset disclaimer

ckanext/ontario_theme/ontario_theme_dataset.json
Access level is a required piece of information for the public data catalogue.
This PR consists of one change (3 commits) to make access level required. Changing "required" to "true" is not sufficient to assure the right form behaviour, the scheming_required validator must be added. The "form_include_blank_choice" flag was set to "true" will make sure the user doesn't just unknowningly go with a set default value for access_level. 
This establishes preferred behaviour: If the user doesn't see/fill out access level, the validator sends them back.
=> Make access level required

ckanext/ontario_theme/templates/organization/snippets/helper.html
This PR consists of one commit and one change: Update the featured content section on the hopepage with a link to the AI and algorithms group.
=> Bug: Fix link to OG leads dataset

ckanext/ontario_theme/templates/internal/home/snippets/ontario_theme_categories.html, ckanext/ontario_theme/templates/internal/home/snippets/ontario_theme_popular_datasets.html, ckanext/ontario_theme/templates/internal/home/snippets/ontario_theme_recent_activity.html
This PR consists of 1 commit to add 3 classes to links in the homepage to track the use of those categories of links.
=> Add classes for GA use to track homepage traffic

ckanext/ontario_theme/plugin.py, ckanext/ontario_theme/templates/internal/organization/read_base.html, ckanext/ontario_theme/templates/internal/package/base.html
This PR consists of 2 commits to:
- add a get_translated function that takes a specified language
- use that function to create ministry-name-fr and dataset-name-fr attributes for GA use on organization and dataset pages
=> Add french ga tags

ckanext/ontario_theme/schemas/external/ontario_theme_dataset.json, ckanext/ontario_theme/schemas/internal/ontario_theme_dataset.json
This PR consists of 1 commit to make 1 change: Add missing geographic breakdowns: Province, Wildlife Management Unit, Forest Management Unit, County, District, and Forward Sortation Area. These are all geographic breakdowns of existing datasets in the catalogue.
=> Add new geographic breakdown options to a package.

ckanext/ontario_theme/fanstatic/external/colours.less, ckanext/ontario_theme/fanstatic/external/ontario_theme.css, ckanext/ontario_theme/fanstatic/internal/accessibility.less, ckanext/ontario_theme/fanstatic/internal/buttons.less, ckanext/ontario_theme/fanstatic/internal/colours.less, ckanext/ontario_theme/fanstatic/internal/general_styles.less, ckanext/ontario_theme/fanstatic/internal/labels.less, ckanext/ontario_theme/fanstatic/internal/ontario_theme.css, ckanext/ontario_theme/fanstatic/internal/smarties.less, ckanext/ontario_theme/templates/external/home/snippets/ontario_theme_featured_content.html, ckanext/ontario_theme/templates/external/home/snippets/ontario_theme_intro.html, ckanext/ontario_theme/templates/internal/header.html, ckanext/ontario_theme/templates/internal/home/layout3.html, ckanext/ontario_theme/templates/internal/home/snippets/ontario_theme_datasets_stats.html, ckanext/ontario_theme/templates/internal/home/snippets/ontario_theme_intro.html, ckanext/ontario_theme/templates/internal/home/snippets/search.html, ckanext/ontario_theme/templates/internal/page.html, ckanext/ontario_theme/templates/internal/snippets/facet_list.html, ckanext/ontario_theme/templates/internal/snippets/search_form.html
This PR consists of 5 commits to make the following changes:
* update colours to accessible colours from the ontario.ca design system
* shift to use of bootstrap's sr-only class for screen-reader-only text
* addition of aria-label and aria-hidden to some buttons that use icons
* update homepage with correct header order and consistent colour contrasting
To do in a future PR:
- headings order needs to be reviewed on other pages
- potentially review all icon buttons in order to add accessible labels
=> Accessibility repair

ckanext/ontario_theme/templates/internal/scheming/form_snippets/organization.html, ckanext/ontario_theme/templates/internal/snippets/facet_list.html
This PR consists of 2 commits to fix cases where display_name is still being used to display an organization's name (instead of get_translated).
=> Fix organization display name

README.rst, ckanext/ontario_theme/plugin.py, ckanext/ontario_theme/schemas/ontario_theme_group.json, ckanext/ontario_theme/templates/internal/group/snippets/group_item.html, ckanext/ontario_theme/templates/internal/group/snippets/info.html, ckanext/ontario_theme/templates/internal/package/group_list.html, ckanext/ontario_theme/templates/internal/scheming/form_snippets/ontario_theme_organization_upload.html, ckanext/ontario_theme/templates/internal/scheming/group/about.html, ckanext/ontario_theme/templates/internal/scheming/group/group_form.html, ckanext/ontario_theme/templates/internal/snippets/group.html
This PR consists of 6 commits to implement fluent groups, including:
- groups schema
- addition of a get_group helper (to account for areas where group extras aren't passed into the template)
- layout fixes to the group form
- changes to group templates to handle bilingual values
=> Fluent groups

ckanext/ontario_theme/plugin.py, ckanext/ontario_theme/validators.py
Refactor validator found in `plugins.py` to `validators.py` that was introduced in PR #156.
=> Improvement: Move plugin validator to validators.py.

ckanext/ontario_theme/templates/internal/snippets/facet_list.html
Ensure choices are set so that the proper display name
is set and displayed for the user. This was commented in PR #162
accidentally.
=> Bug: Uncomment setting choices.

ckanext/ontario_theme/templates/internal/footer.html
The queen's printer message date span should reflect the current year. Updated for 2020.
=> Task: Update queen's printer message.

ckanext/ontario_theme/i18n/fr/LC_MESSAGES/ckanext-ontario_theme.po, ckanext/ontario_theme/plugin.py, ckanext/ontario_theme/templates/external/header.html
The ontario.ca survey accepts "id" and "page" parameters that are included in survey results. This PR includes those parameters in the survey url.
=> Add parameters to ontario.ca survey url

ckanext/ontario_theme/i18n/fr/LC_MESSAGES/ckanext-ontario_theme.po, ckanext/ontario_theme/templates/internal/package/snippets/resources_list.html
- added logic to display "This dataset has no supporting files" when number of non-data resources is 0
=> Task: Display "no supporting files" when no support files are available

ckanext/ontario_theme/plugin.py
- changed to store columns in an ordered dictionary due to python 2 default behavior of storing dictionary items in unordered pairs
- changed to use utf-8 with BOM due to excel display issues
- updated file name and include a datastamp
- changed url to /dataset/inventory instead of /dataset/csv_dump
=> Task: Modified csv_dump to produce ordered columns at /dataset/inventory

ckanext/ontario_theme/templates/internal/snippets/facet_list.html
Now that groups are fluent-y, they must use title_translated instead of display_name. Update this in the facet list.
=> Bug: Group facet list must use title_translated.

ckanext/ontario_theme/plugin.py
- due to the way the activity stream is constructed, there does not seem to be a simple way to pass in a string to use ckan's built in translation methods; as such, the translation is done in the custom function depending on user's language setting.
=> Task: anonymize the actvity stream for users that are not logged in.

ckanext/ontario_theme/plugin.py, ckanext/ontario_theme/schemas/external/ontario_theme_dataset.json, ckanext/ontario_theme/schemas/internal/ontario_theme_dataset.json
- changed all instances of 'unnamed resource' to show 'data'
- modified help text to provide better guidance on naming convention for resource editors
=> Task: Change default text for resources to 'Data' when it's left blank

ckanext/ontario_theme/templates/internal/base.html, ckanext/ontario_theme/templates/internal/page.html
Changes to page.html and base.html create conflicts. Google tag manager snippets can be abstracted out for smoother merges.
=> Task: Abstract out Google Tag Manager snippet for smoother merges.

ckanext/ontario_theme/schemas/external/ontario_theme_dataset.json, ckanext/ontario_theme/templates/internal/scheming/package/resource_read.html
This PR includes:
- changing the label for data_last_updated to match the case of other resource field labels
- remove data_last_updated from the list of fields to be displayed in the "additional info" section of the resource page
- change "Last updated" display to show data_last_updated if it's available (if not, show last_modified or created)
=> Resource attribute adjustments

ckanext/ontario_theme/fanstatic/internal/general_styles.less, ckanext/ontario_theme/fanstatic/internal/ontario_theme.css, ckanext/ontario_theme/fanstatic/internal/ontario_theme_lock_if_odc.js, ckanext/ontario_theme/harvesters/__init__.py, ckanext/ontario_theme/harvesters/ontario_data_catalogue.py, ckanext/ontario_theme/plugin.py, ckanext/ontario_theme/schemas/internal/ontario_theme_dataset.json, ckanext/ontario_theme/templates/internal/package/snippets/resource_item.html, ckanext/ontario_theme/templates/internal/scheming/form_snippets/extrafields_fluent_title.html, ckanext/ontario_theme/templates/internal/scheming/form_snippets/fluent_markdown.html, ckanext/ontario_theme/templates/internal/scheming/form_snippets/fluent_text.html, ckanext/ontario_theme/templates/internal/scheming/form_snippets/hidden.html, ckanext/ontario_theme/templates/internal/scheming/form_snippets/markdown.html, ckanext/ontario_theme/templates/internal/scheming/package/read.html, ckanext/ontario_theme/templates/internal/scheming/package/snippets/additional_info.html, ckanext/ontario_theme/templates/internal/scheming/package/snippets/package_form.html, ckanext/ontario_theme/templates/internal/snippets/search_result_text.html, ckanext/ontario_theme/validators.py, setup.py
This PR consists of:
- a harvester for the Ontario data catalogue
- a validator that prevents the changing of certain fields harvested through the validator
- an authorization mod that prevents the changing of resources harvested through the validator
- the removal of the node_id field
- the addition of a colby notes field specifically for internal notes
=> Ontario Data Catalogue Harvester

test.ini
Modifies the paths in `ckan.ini` to be relative to the new path of ontario theme in `/usr/lib/ckan/default/src`.
#208 
Check that moving the theme to `/usr/lib/ckan/default/src` with these path changes in `ckan.ini` works fine.
=> Move ontario theme out of ckan source directory

config/README.rst, config/solr/managed-schema, scripts/README.rst, scripts/setup_solr.sh
Provides:
- a [bash script](https://github.com/ongov/ckanext-ontario_theme/blob/solr8/scripts/setup_solr.sh) to install Solr 8.11.1 in its own VM
- a [config file](https://github.com/ongov/ckanext-ontario_theme/tree/solr8/config/solr) customized for Ontario ckan
- documentation for both
- check that you approve of the script code and passing of the sudo credentials as an environment variable
- the script is specific to the `solr8` branch; once the branch is finally merged, [this line to switch branches](https://github.com/ongov/ckanext-ontario_theme/blob/solr8/scripts/setup_solr.sh#L25) is no longer necessary. Shall I remove it now already?
- read over the documentation for anything that is not clear
=> Bash script to install Solr 8

ckanext/ontario_theme/fanstatic/internal/ontario_theme_download_tracker.js, ckanext/ontario_theme/templates/internal/base.html, ckanext/ontario_theme/templates/internal/gtm_pageview.html, ckanext/ontario_theme/templates/internal/package/resource_read.html, ckanext/ontario_theme/templates/internal/package/snippets/resource_item.html
Implements a new JS function `trackDownload()` that is triggered every time a download button or download URL is clicked. The dataLayer object is sent to Google analytics for further processing.
- #243
- small fix in passing group  name for #237 in `ckanext/ontario_theme/templates/internal/base.html` and `ckanext/ontario_theme/templates/internal/gtm_pageview.html`)
The functionality of the code has already been reviewed from the Google analytics side. The reviewer here can generally review the code. The CKAN docs suggest creating a [JS module](https://docs.ckan.org/en/2.9/contributing/frontend/javascript-module-tutorial.html#building-a-javascript-module), but `ckan.module` was not recognized and as an alternative, an ordinary JS function was created instead.
=> GA download tracker (CKAN 2.8)

ckanext/ontario_theme/schemas/external/ontario_theme_dataset.json, ckanext/ontario_theme/schemas/internal/ontario_theme_dataset.json
Same as PR #250 but for CKAN 2.8.
Code change is identical, but includes for internal schema as well.
=> Adds Ontario Forest Region geo breakdown for ckan2.8

ckanext/ontario_theme/fanstatic/common.css, ckanext/ontario_theme/fanstatic/external/ontario_theme.css, ckanext/ontario_theme/fanstatic/fonts_googleapis.css, ckanext/ontario_theme/fanstatic/internal/ontario_theme.css, ckanext/ontario_theme/fanstatic/internal/webassets.yml, ckanext/ontario_theme/fanstatic/webassets.yml, ckanext/ontario_theme/plugin.py, ckanext/ontario_theme/templates/internal/base.html, ckanext/ontario_theme/templates/internal/page.html, ckanext/ontario_theme/templates/internal/snippets/home_breadcrumb_item.html
This PR accomplishes the same as PR #248, but for CKAN 2.9. The code changes are not the same because of the way assets are defined: CKAN 2.9 uses `.yml` files.
Differences:
- a `ckanext/ontario_theme/fanstatic/webassets.yml` file created to define location of the css files in the `fanstatic` root dir
- the common css files are also defined in `ckanext/ontario_theme/fanstatic/internal/webassets.yml`
Commonalities:
- common css file for breadcrumbs stored in `fanstatic` root directory and removed from internal and external `ontario_theme.css`
- `fanstatic` root directory defined in `ckanext/ontario_theme/plugin.py` for both internal and external sites
- the css assets need only be imported in `ckanext/ontario_theme/templates/internal/base.html` and not also in the external `base.html`
- …
=> Update breadcrumb styling to match Ontario Design System (CKAN 2.9)

ckanext/ontario_theme/fanstatic/internal/webassets.yml
Error "Uncaught ReferenceError: ckan is not defined" is no longer displayed in the console when the Edit button of a package is clicked. See details: https://github.com/ongov/ckanext-ontario_theme/issues/246
#246 
Please verify that 
- the error no longer displays in the console when clicking on the Edit button of a package
- `main.js` is getting loaded prior to `ontario_theme_lock_if_odc.js` in the network tab
=> preload main.js in ontario_theme_lock_if_odc.js module. Closes #246

ckanext/ontario_theme/fanstatic/common.css, ckanext/ontario_theme/fanstatic/external/ontario_theme.css, ckanext/ontario_theme/templates/external/home/snippets/ontario_theme_resources_and_information.html, ckanext/ontario_theme/templates/internal/home/layout3.html
- Aligns homepage to Figma
- Left-aligns 'Topics'
- Removes padding from page alert
- Adds margins to "Resources and information"
- Change dataset headings to `h2`
- Change "Resources and information" subheadings to `h3`
- Homepage is responsive
- Homepage follows the Figma design
=> Aligns homepage to Figma.

ckanext/ontario_theme/templates/internal/group/index.html, ckanext/ontario_theme/templates/internal/group/read.html, ckanext/ontario_theme/templates/internal/organization/read.html, ckanext/ontario_theme/templates/internal/package/search.html
- Replaces `title_string` in filter query to `name` in the datasets search page and individual group and organization pages
- Broken sorting methods on Organizations and Datasets pages
- Both “Name ascending” and “Name descending” methods only show some ministries and datasets in alphabetical order, some not sorted properly.
- Name ascending and name descending sort works correctly on organizations and datasets search pages. 
- Name ascending and name descending sort works correctly on organizations and group individual pages.
=> Ckan 2.9 name sort

ckanext/ontario_theme/fanstatic/common.css, ckanext/ontario_theme/templates/external/scheming/package/read.html, ckanext/ontario_theme/templates/internal/package/snippets/additional_info.html, ckanext/ontario_theme/templates/internal/package/snippets/resources_list.html, ckanext/ontario_theme/templates/internal/snippets/organization.html
Fixes heading levels in the individual dataset page as per figma mockup.
- h3.module-heading for organization title
- h2 and h3 hierarchy followed for headings in the order they appear in figma
- check that the headings have all been properly fixed
- an override category was added in `common.css` for `.embedded-content h2`. Do you think we should also have overrides for embedded h3, h4, etc in case someone uses them when creating the description of their dataset?
=> heading levels for individual dataset page

ckanext/ontario_theme/templates/internal/group/edit_base.html, ckanext/ontario_theme/templates/internal/group/read_base.html, ckanext/ontario_theme/templates/internal/organization/edit_base.html, ckanext/ontario_theme/templates/internal/organization/read_base.html, ckanext/ontario_theme/templates/internal/package/read_base.html, ckanext/ontario_theme/templates/internal/package/snippets/resource_views_list_item.html
Remove the little icons beside the inner tab navigation (e.g. little clocks, edit pencils, etc), as per the figma design.
- confirm the icons are gone from the tab navigation
- check that there aren't any others that I have missed
=> Remove icons from inner tab navigation

ckanext/ontario_theme/templates/internal/package/base.html
- Translates the breadcrumb for Ministries when in dataset pages
- That the breadcrumb for Ministries is translated when toggled in French mode, specifically when navigating to an individual dataset from a Ministry or from the dataset search page
=> Ckan 2.9 French breadcrumb translation

ckanext/ontario_theme/templates/internal/package/snippets/resources_list.html
If a package is not open (i.e. restricted or under review), users who are do not have write access (i.e. users who are not sysadmins or org admins) should not be able to see the resource list. 
Please confirm that the resource list of a package with access level that is not open is only displayed for sysadmins or org admins.
=> allow only write-access users to see resources in non-open pkgs

ckanext/ontario_theme/fanstatic/common.css
Increases the z-index of the group search bar to be above the secondary column. The secondary's z-index was blocking the left side of the input field.
The search bar on the Groups page only accepts input if the mouse is about 1/3 the distance from the left of the input box. 
The search bar on the groups page can accept input at any point on the input box and the cursor is in input style.
=> CKAN 2.9 group search

ckanext/ontario_theme/fanstatic/common.css, ckanext/ontario_theme/templates/internal/header.html
Updates the header according to the designers suggestions
- Francais link on mobile should remain a full word “Francais“ with no underline
- The Design System suggest having an overlay under the menu drop down to show the hierarchy of the elements. On tablet and mobile the screen is being darkened. 
- Menu button moving to the left and right when pressing it to open and close the drop down
- French link is correctly displaying “Francais“ with no underline 
- When clicking to open the menu, there is an overlay on the page. 
- Transition between the open menu and close menu buttons are seamless.
=> CKAN 2.9: Header design review updates

ckanext/ontario_theme/plugin.py, ckanext/ontario_theme/templates/internal/package/snippets/report_an_error.html
Fixes adding a new resource 502 gateway error caused by callout
Displays resource type if no name is provided and if no name and no type is provided for a resource, "Supporting file" is displayed as the id in the URL
Users can add new resources without a 502 error
Survey URL id parameter displays resource type if there is no resource name entered, but there is a resource type.
Survey URL id parameter displays "Supporting file" when there is no resource type and no resource name.
Survey URL id parameter displays resource name, when name is provided.
=> Ckan 2.9 callout fix

ckanext/ontario_theme/fanstatic/common.css, ckanext/ontario_theme/templates/internal/scheming/package/resource_read.html
- Removes [comment blocks around the re-designed Data API section](https://github.com/ongov/ckanext-ontario_theme/compare/ckan_2.9_upgrade...ckan_2.9_apibtn#diff-546c82ec74a181757732192978e8194f81304d3e199d717bcb7c19784be08697L104) made previously according to figma. 
- Clicking on the link brings up the same info panel as before that explains how to use the API
- Panel width and content widths are properly formatted for various screen sizes
- Formats entire `resource_read.html` file with proper indentation
Please verify that:
- the Data API section works as expected
- the info panel that pops up when clicking the link is formatted properly on various screen sizes
=> Activate Data API section

ckanext/ontario_theme/templates/internal/organization/index.html
On mobile and tablet, the Ministries on the Ministry search page were not clickable. The survey feedback link was creating this bug.
On mobile and tablet, the Ministries on the Ministry search page are clickable and redirect to the individual Ministry's page
=> CKAN 2.9 Ministry search page bug

ckanext/ontario_theme/fanstatic/common.css, ckanext/ontario_theme/templates/internal/package/search.html
The filter modal is blocked by the navigation bar and users are incapable of closing the modal without refreshing the page. This problem is only on the dataset search page on screen widths < 765px. (For individual group and Ministry pages the filter results button is too low on the page to cause this problem)
On 765px and smaller screens, the navigation bar should be behind the modal on the dataset search page. The individual group and Ministry pages should be tested as well.
=> Ckan 2.9 Filter modal bug

ckanext/ontario_theme/fanstatic/common.css
Provides cross-browser support for placeholder styling
The French placeholder text is too long for mobile. This issue was previously fixed in #286 but the solution on worked for Firefox. This PR is to align other browsers with Firefox.
In browsers, such as Edge, Safari, Firefox, and Chrome, long placeholders throughout the site should have an ellipsis and not be abruptly cut off. 
**(Left is the issue being fixed and right is what the PR accomplishes)**
=> CKAN 2.9 placeholder cross browser compatibility

ckanext/ontario_theme/fanstatic/common.css, ckanext/ontario_theme/fanstatic/external/ontario_theme.css, ckanext/ontario_theme/templates/external/package/snippets/ontario_theme_access_level.html, ckanext/ontario_theme/templates/external/scheming/package/read.html, ckanext/ontario_theme/templates/external/scheming/package/snippets/additional_info.html, ckanext/ontario_theme/templates/internal/package/read.html, ckanext/ontario_theme/templates/internal/package/read_base.html, ckanext/ontario_theme/templates/internal/package/snippets/resource_item.html, ckanext/ontario_theme/templates/internal/package/snippets/resources_list.html, ckanext/ontario_theme/templates/internal/snippets/license.html, ckanext/ontario_theme/templates/internal/snippets/organization.html
[DATA-546](https://ontariodigital.atlassian.net/browse/DATA-546)
- Moves left-hand items to the right side
- Removes the images associated with ministries
- Removes the “Groups” tab from the navigation bar
- Moves the “Additional Information” section above the resources
- Suppresses empty metadata fields in the "Additional Information" section.
- Removes the green box with checkmark that says "Data available"
- Changes the heading Data to the dataset name
- Adds a ministry contact link at the bottom of the dataset description - (DATA-632)
- Changes the date range format to Month Day, Year
- There are a few files where I have commented out previous code instead of removing it.
- Translations have not been added to the .po / .pot files, nor has it been compiled.
- ` h.render_datetime` is …
=> Ckan 2.9 upgrade dataset

ckanext/ontario_theme/fanstatic/common.css, ckanext/ontario_theme/fanstatic/external/ontario_theme.css, ckanext/ontario_theme/templates/internal/package/snippets/resource_item.html
Update the file type labels
- update the color of file type labels and remove the pseudo 3D styling to keep them as plain rectangles with rounded corners 
- Font color #000, font weight: 600
- File type labels are in the correct colour and font weight on the dataset search and individual dataset/ministry/group page
- Padding and font sizes/font weight are different on the Figma (I added the Figma to the ticket for visual color reference) but the ticket only asks for the color and font weight changed. This may be something to add to dataset search page, if needed. As this PR only reflects the ticket.
=> CKAN 2.9 file type labels

ckanext/ontario_theme/templates/internal/group/snippets/group_item.html, ckanext/ontario_theme/templates/internal/group/snippets/info.html, ckanext/ontario_theme/templates/internal/snippets/group.html
Removes block that displays a profile image from the Groups pages
Confirm that no image is displayed on any Group page
=> Remove image profile pic from groups

ckanext/ontario_theme/fanstatic/common.css, ckanext/ontario_theme/fanstatic/external/ontario_theme.css, ckanext/ontario_theme/templates/external/home/help.html, ckanext/ontario_theme/templates/internal/home/about.html
- Padding has disappeared on mobile About and Help pages. Please restore to 15px padding left/right
- Padding in mobile for both the About and Help pages should be 15px on the left and right and aligns with the navigation bar
=> About and Help page padding

ckanext/ontario_theme/plugin.py, ckanext/ontario_theme/templates/internal/snippets/ontario_theme_keywords_facet.html
- changes "keywords"/"mot clées" to "topics"/"sujets" in search results box
- In the search results box and the filter headings "topics"/"sujets" should be displayed instead of "keywords"/"mot clées"
I am not taking into account pluralization.
=> Ckan 2.9 keyword text

ckanext/ontario_theme/templates/internal/package/search.html
Removes the API link at the bottom of the datasets search page:
Verify that this line is gone from the bottom of the dataset search page.
=> Removes API link at bottom of dataset search page

ckanext/ontario_theme/templates/internal/scheming/package/resource_read.html
* Only allow admin/sysadmins access to data that is not open. Users not having these permissions or that are not logged in are not shown resource information.
* Users not logged in can access under-review/restricted URLs and view the resource contents
* if-else condition placed in `{% block pre_primary %}`
* if condition placed in `{% block primary %}`
* open/under-review/restricted resource pages load for logged in user.
* open resource pages load for not-logged in user.
* under-review/restricted resource url when accessed by a not-logged in user displays "Resource not available", and no resource related info is leaked.
=> Display resource page content only if dataset is open or user admin

ckanext/ontario_theme/plugin.py, ckanext/ontario_theme/templates/internal/organization/index.html
Prevents the function that sorts organization names from being called when there are no organizations in the application.
- Check on the pre-launch version that the Ministries tab does not crash.
- Check on local version that Ministry sort and search still works the same
=> prevent orgs from being sorted on initial launch

ckanext/ontario_theme/templates/internal/group/snippets/group_list.html
Fixes the broken group page by adding a check to use group title if no titles are translated.
Confirm that group page displays when a group does not have a `title_translated` field.
=> Fix broken group page

ckanext/ontario_theme/templates/internal/group/read.html, ckanext/ontario_theme/templates/internal/organization/read.html, ckanext/ontario_theme/templates/internal/package/search.html
Sets the default sort order of datasets to Relevance instead of Last Modified.
Check that Relevance is the default sort order of datasets when:
1. First landing on the Dataset search page
2. Opening a dataset from the Ministry search page
3. Selecting a Group from the Groups page
Also check:
- if the user selects own sort order, that sort order is preserved after interactions such as using the search bar or paginating through the list of datasets
- equivalent functionality of all of the above in French
=> make Relevance the default sort order

ckanext/ontario_theme/fanstatic/common.css
Fixes improper formatting of the API modal in Safari browser.
- Open the API modal in Safari browser and verify that the formatting is ok.
- Check that the fix does not mess up the API modal in other browsers
=> fix api modal layout for safari by adding min-width

ckanext/ontario_theme/templates/internal/base.html
- Removes the webservices.gov.on.ca script from the code
- Using components with unpatched vulnerabilities can increase the risk profile of the application and can be exploited by attackers under certain conditions
- On local, there should be no reference of a webservices.gov.on.ca script
- Test / Stage must also be reviewed as there is a second script that will not run on localhost. Confirm there are no references of webservices.gov.on.ca js file or php file on Stage and/or Test.
=> Fix vulnerable JavaScript dependency

ckanext/ontario_theme/templates/internal/header.html
- Redirects users to the logout page after pressing the logout button
- Logout button erroneously had a '_' at the beginning of the logout html file in the relative path, causing issues with actually logging users out when the button was pressed.
- On test or stage (because local works fine), users should be redirected to the logout page after clicking the logout button. 
- Hovering over the logout button, the path should end with `user/logout` (no '_')
=> Logout button fails

ckanext/ontario_theme/templates/internal/ajax_snippets/api_info.html
- Removes SQL query from CKAN api calls module
- ODC has sql queries disabled. The Data API popup gives example of sql query that ends up in an error when executes.
- In the CKAN data API calls module, the `Query (via SQL)` endpoint and querying examples are removed. (There should be 3 endpoint table entries, and 2 querying examples)
=> Bug: Removes SQL query from CKAN api calls module

ckanext/ontario_theme/plugin.py
Places checks on `resource_name` attributes in function `extract_package_name()` that was causing errors in the `uwsgi.ERR` log file.
To make sure the code checks for all possibilities, upload new resources with different combinations of name and type and make sure there are no errors in `uwsgi.ERR` or on the page:
- no name, no type 
- no name, but type Data
- no name, but type Information
- add a name, but no type
- add a name and a type (try different types)
Test the above for uploaded CSV resources and for link URLs.
=> add checks to resource name and type

ckanext/ontario_theme/templates/internal/user/logout_first.html
- Removes underscore from logout button path on login page
- Logout Link has an underscore in path name. This causes the pages not to redirect to the logout page correctly.
- **This needs to be tested on Test or Stage because the bug is not reproducible on local**
- When a user that is logged in navigates to the `user/login` page and is prompted to logout because they are "already logged in" the `Log out now` button should have the path `user/logout`
- When pressing the `Log out now` button, users should be redirected to log out.
=> Bug: Removes underscore from logout button path on login page

ckanext/ontario_theme/fanstatic/common.css, ckanext/ontario_theme/resource_upload.py, ckanext/ontario_theme/templates/internal/scheming/package/resource_read.html
- Creates the "WEB" file type format label and adds `#ebe7db` colour to the label
- Capitalizes inputted file types (except GeoJSON) for new resources. (Does not apply to existing resources)
- Removes file size from the resource additional information table for remote hosted resources
- Attaches the "WEB" label to resources hosted remotely with no file type format listed
- "WEB" label is discoverable
- The Format in the Additional Information table is now “WEB”
- Currently, if the Format field is left blank, it will be listed on the Dataset page with file type label “Other”
- The “Format” field of Resources that are hosted remotely via the “Link” button should default to “Web” if the user does not input anything.
- The “File size” field in the Additional Information table of the resource …
=> Creates WEB resource format type

ckanext/ontario_theme/fanstatic/common.css, ckanext/ontario_theme/fanstatic/external/ontario_theme.css, ckanext/ontario_theme/templates/internal/home/snippets/ontario_theme_categories.html
- Put topics into a list
- Moved the numbers outside the a tag, to remove conflict with GA4
- The number of datasets shouldn’t be a part of the URL because it breaks the GA statistics. Move the count outside of the <a href tag.
- Numbers are not in the href
- Clicking the image or text, the blue focus border is around both the text and the image (not the number)
- Hovering over the text or image will change the colour of the image and underline the text (not the number)
- Numbers do not appear in GA4
=> Homepage topic links

ckanext/ontario_theme/fanstatic/common.css
- Fixes overlap on dataset page on iPhone 5 and screens of similar widths
- There is no overlap on the dataset page for the file labels on iPhone 5 or screens of similar widths.
=> Fixes file label overlap on dataset page on iPhone 5

scripts/README.md
Removes outdated fetch of branch `ckan_2.9_upgrade` from the Solr README instructions
=> rm fetch to old branch from readme

ckanext/ontario_theme/resource_upload.py
- When running the load_organizations_data.py, all resources being loaded will get an internal 500 error. 
- This PR includes a minor fix and a check for packages with resources
- Running load_organization_data.py, you do not get an internal 500 error
- Add a resource, input a random/unique lowercase file format. On the dataset page, in the formats facet box on the dataset search page, and in the api `/api/3/action/resource_show?id=<id>`, the format is in all uppercase.
=> Fixes internal 500 error when using load_organization_data.py

ckanext/ontario_theme/resource_upload.py, ckanext/ontario_theme/templates/internal/package/snippets/resource_item.html
- Displays correct mimetype in the additional information page on the resource page `application/geo+json`
- Displays correct label on dataset page
- Additional information table on resource page has correct mimetype
- The GeoJSON file label is displayed, as opposed to “Other” on the dataset page
**Notes**
- if you change an existing resource, you will have to rebuild the search index
=> DATA-1145 GeoJSON format is not displayed correctly on dataset page

ckanext/ontario_theme/fanstatic/common.css
- When you hover over the dataset resource title the underline touches the the white border
- This should no longer be happening.
- DATA-1017
=> Fixes link touching label

ckanext/ontario_theme/templates/external/scheming/package/snippets/additional_info.html, ckanext/ontario_theme/templates/internal/scheming/package/resource_read.html
- The user will see the dates in format "Month Day, Year" in the dataset additional information table
- Date format across the website should be “Month Day, Year”
- formatted html
- Dataset with any of the following metadata should be in "Month Day, Year" format instead of "YYYY-MM-DD" in additional information table
- Last Validated Date (current_as_of)
- Opened date (opened_date)
=> DATA-1171: Additional Information dates are in incorrect format on dataset page

ckanext/ontario_theme/templates/internal/scheming/package/resource_read.html, ckanext/ontario_theme/templates/internal/snippets/translate_facets.html
- Uses attribute access for ckan.model.license but adding `,_data` to additional information and facet licence references
- Stops the following warning from populating in uwsgi.ERR:
``` 
Function __getitem__() in module ckan.model.license has been deprecated and will be removed in a later release of ckan. License.__getitem__() is deprecated and will be removed in a future version of CKAN. Instead, please use attribute access. 
```
- While navigating the site, everything works and the warning no longer appears in the logs.
=> Fixes deprecated warning in uwsgi.ERR

ckanext/ontario_theme/fanstatic/common.css, ckanext/ontario_theme/templates/internal/organization/activity_stream.html, ckanext/ontario_theme/templates/internal/organization/index.html, ckanext/ontario_theme/templates/internal/organization/read_base.html, ckanext/ontario_theme/templates/internal/package/search.html, ckanext/ontario_theme/templates/internal/page.html, ckanext/ontario_theme/templates/internal/scheming/organization/about.html
- Removes CKAN core grid system from Ministry page 
- Removes CKAN core grid system from page.html
- Adds subsequent DS grid to pages affected
- Removes hidden h1 from activity stream page
- Fixes spacing
- ministry’s activity stream page heading overlaps with the activity stream
- the navigation tabs are unusable
- Page alignment is correct on both left and right
- ministry’s activity stream page heading no longer overlaps with the activity stream
- the navigation tabs work as expected
=> Fixes ministry activity stream from overlapping with heading

ckanext/ontario_theme/fanstatic/common.css, ckanext/ontario_theme/templates/internal/snippets/facet_list.html
- Switches show more button in facets to a tertiary button
- Changes colour of visited links for buttons to the same colour as the normal state.
- Facet lists have the show more button as a tertiary button
- Buttons that have been visited show the text in the same colour as the normal state on the facets and on the dataset page
=> Task: Switches show more to a tertiary button

ckanext/ontario_theme/templates/internal/snippets/package_item.html
- Remove Algorithm / AI label from the datasets
- The blue "Algorithm/AI" label does not appear next to the titles of the Datasets on the Datasets search page or Individual Ministries and Groups pages.
=> [Task]: Removes algorithm/ai label from dataset search page

ckanext/ontario_theme/templates/internal/scheming/group/about.html
- Allows HTML tags in the groups markdown tag. This is to only allow for abbreviations to be added using `<abbr>` tags
- Removes the `<h1>` in the body, as there is already an `<h1>` on the page.
- Allowing the HTML tags will allow me to go in and add the necessary abbreviation tags to the AI group description. Once that is done, the ticket will be ready for QA by designers
- There is only 1 `<h1>` tag on the groups about page. 
- Adding inline HTML tags in the groups description works.
=> [Task]: AI and COVID-19 group pages minor markup fixes

ckanext/ontario_theme/templates/external/home/snippets/ontario_theme_intro.html
- interim solution for IDC title change, consequently the titles for other environments (except prod).
(editing title in Admin config UI)
- sites with title "Ontario Data Catalogue" display the correct title and translation
- sites that do not have title "Ontario Data Catalogue" display the site title.
=> [Task]: Header change IDC

ckanext/ontario_theme/templates/internal/package/read_base.html
- Removes RSS box from the Dataset page
-RSS function has an extremely low engagement rate and is an unfamiliar functionality to the majority of our users. Removing the “Keep updated“ box from the right side bar will allow for more important content to take it’s place
- User doesn’t see the “Keep updated“ box on the Dataset page
=> [Task]: Remove the RSS box from the Dataset page

ckanext/ontario_theme/templates/internal/package/snippets/resources_list.html
- Hides supporting files heading when there are no supporting files in the Dataset page
- Dataset with no supporting files doesn’t display the heading “Supporting Files“ and “This dataset has no supporting files“ text .
=> [Task]: Hide Supporting Files heading when there are no supporting files

ckanext/ontario_theme/fanstatic/common.css, ckanext/ontario_theme/templates/external/package/snippets/ontario_theme_access_level.html, ckanext/ontario_theme/templates/internal/package/read.html, ckanext/ontario_theme/templates/internal/package/snippets/resources_list.html
- Redesigns the restricted and under review callouts
- Redesigns the AI callout
- Remove heading for restricted and under review datasets
- DATA-1094
- Restricted dataset: bgcolor: #FCEFF0 , border: #CD0000 1px
- Under review dataset: bgcolor: #F1E3F2 , border: #92278F 1px
- The callout box design (not content) looks like in the mock up (see ticket)
=> Redesign the access level & AI callout boxes

ckanext/ontario_theme/fanstatic/common.css, ckanext/ontario_theme/templates/internal/group/snippets/group_item.html, ckanext/ontario_theme/templates/internal/group/snippets/group_list.html, ckanext/ontario_theme/templates/internal/organization/index.html, ckanext/ontario_theme/templates/internal/organization/snippets/organization_item.html, ckanext/ontario_theme/templates/internal/organization/snippets/organization_list.html
- Matches Ministries list items design to the table in the Groups page
- Switches Groups page design from div to list
- Makes entire list item row clickable as link
- Gives accessible name and description (if needed) to link 
- When a user places their mouse cursor over the row - the whole row changes the look to mouse-hover and acts as a hyperlink.
- Mirrors the design from the Groups page (a table) on the Ministries page (a list)
- The design of the groups list on the Groups page and Ministries page look identical with the exception of Groups page having a short group description underneath the group name. 
- The interaction of the groups table: on mouse hover on both pages whole row is getting highlighted and acts as a hyperlink.
=> [Task]: Groups page should be aligned to the Ministries page

ckanext/ontario_theme/fanstatic/common.css, ckanext/ontario_theme/fanstatic/external/ontario_theme.css
- Align the font size on pages across website
- Changes a font colour on dataset page
- DATA-1332
- Individual search pages:
- Search box label: font size 19px
- Dataset name - font size 20px
- Ministry name - font size 16px
- Dataset description - font size 16px
- “Resource formats” - font size 16px
- “Show more” - font size 16px
- Search input field - font size 20px
- Dataset pages:
- Body text - font size 16px
- Additional information table content - font size 16px
- “Learn more about accessing data using different formats.” - font size 16px,  colors: black & hyperlink blue.
- Gray boxes body text: font size 16px
- **Resource list**
- Dataset name - font size 18px
- File size - font size 16px
- Last updated - font size 16px
- Language: English / French - font size 16px
- Resource …
=> [Task]: Align the font size & colour across the website

ckanext/ontario_theme/fanstatic/common.css
- Changes font size and dimensions of dataset search page file type label
- Changes font size and dimensions of dataset page resource file type label
- DATA-1333
- Individual search pages file type label:
- Dataset pages file type label:
=> [Task]: Align font and size of file type labels

ckanext/ontario_theme/templates/internal/snippets/search_form.html, ckanext/ontario_theme/templates/internal/snippets/translate_facets.html
- Displays facet pills when search bar term is not found
- Code clean up
- DATA-1376
- Facet pills work with various scenarios, including 
- when search bar term is found
- when search bar term is not found
- with different filters used
=> [Bug]: Facet pill disappears when searchbar term is not found

ckanext/ontario_theme/templates/internal/group/snippets/group_item.html, ckanext/ontario_theme/templates/internal/organization/snippets/organization_item.html
- Adds data attributes for QA on Ministries page and Groups page.
- Attributes are of the links to click onto a Ministry/Group and on the count
- DATA-1387
- `data-nw` attributes are on Ministry/Group page links and on count
=> [Bug]: Object Identification using data attributes

ckanext/ontario_theme/templates/internal/package/activity.html, ckanext/ontario_theme/templates/internal/package/group_list.html
- Ld+json script was causing a 500 error on the dataset's groups and activity stream pages, due to not being able to find `schema`
- DATA-1369 
- PR #455 
- ld+json script appears on dataset 'asset' page.
- navigating to the groups and history pages do not cause an error
=> [Fix]: ld+json script causing 500 error on dataset's pages

ckanext/ontario_theme/plugin.py, ckanext/ontario_theme/templates/internal/group/read.html, ckanext/ontario_theme/templates/internal/organization/read.html, ckanext/ontario_theme/templates/internal/package/search.html, ckanext/ontario_theme/templates/internal/snippets/package_list.html, config/solr/managed-schema, config/solr/solrconfig.xml
- Uses solr to sort French package/dataset titles on search pages in correct order, including accents and lowercase letters
- Improves performance of French name ascending/descending sort on search pages
- DATA-1162
- Consult ticket for directions on how to implement changes
- Check that the datasets on all search pages are sorted correctly in French when `Name Ascending` and `Name Descending` are chosen.
=> [Bug]: French sorting for datasets does not lead to correct results

ckanext/ontario_theme/plugin.py, ckanext/ontario_theme/templates/internal/footer.html
- Changes catalogue footer to auto-update the end date for King's Printer
- DATA-236
- Footer end date is updated to current date
- code looks fine
=> [Task]: Change catalogue footer to auto-update the end date for King's Printer applicable date range

ckanext/ontario_theme/plugin.py, ckanext/ontario_theme/schemas/external/ontario_theme_dataset.json, ckanext/ontario_theme/validators.py
- Creates validator to strip whitespace from fluent fields.
- Adds validator to dataset and resource schemas for titles and names
- DATA-1392
- When creating/updating a dataset and/or resources with EN and FR titles that start or end with a space, the whitespaces get trimmed.
- When sorting `Name Ascending`, these datasets don't appear out of sort order at the beginning of the list.
=> [Task]: Add a ckan validator to trim whitespace from EN and FR titles

ckanext/ontario_theme/fanstatic/common.css, ckanext/ontario_theme/organization.py, ckanext/ontario_theme/plugin.py, ckanext/ontario_theme/templates/internal/organization/index.html, requirements.txt
- Removes pagination from Ministries' page
- Displays all Ministries on one page
- Implements natsort for sorting Ministry titles
- Reduces Ministries' page loading time
- Reworks Ministries' index view function to return all fields for faster and more efficient sorting
- DATA-1389
- For testing:
- set `ckan.group_and_organization_list_all_fields_max = 100` in the ckan.ini
- run `pip install -r requirements.txt` (in virtual environment) for the `natsort` library
- Ministries' page should have all ministries on one page and no pagination
- Ministries in English and French should be sorted correctly.
=> [Bug]: Sorting on Ministries is not implemented

ckanext/ontario_theme/fanstatic/common.css, ckanext/ontario_theme/templates/external/scheming/package/snippets/additional_info.html, ckanext/ontario_theme/templates/internal/package/snippets/additional_info.html, ckanext/ontario_theme/templates/internal/scheming/package/resource_read.html
- change Addtional Information table from `<table>` to `<div>`s
- DATA-1043
- Tables look the same as prod in all screen sizes
- Tables are made up of divs and not inside of a `<table>`
=> [Task]: change Addtional Information table from <table> to <div>s

ckanext/ontario_theme/templates/internal/snippets/search_form.html
- Adds condition to facet search to prevent `TypeError: unsupported operand type(s) for +: 'NoneType' and 'Markup'` this error being thrown intermittently.
- `TypeError: unsupported operand type(s) for +: 'NoneType' and 'Markup'` error is no longer thrown.
=> Condition to prevent Nonetype concatenate error

ckanext/ontario_theme/fanstatic/common.css, ckanext/ontario_theme/organization.py, ckanext/ontario_theme/plugin.py, ckanext/ontario_theme/templates/internal/organization/index.html, requirements.txt
- Removes pagination from Ministries' page
- Displays all Ministries on one page
- Implements natsort for sorting Ministry titles
- Reduces Ministries' page loading time
- Reworks Ministries' index view function to return all fields for faster and more efficient sorting
- DATA-1389
- For testing:
- set `ckan.group_and_organization_list_all_fields_max = 100` in the ckan.ini
- run `pip install -r requirements.txt` (in virtual environment) for the `natsort` library
- Ministries' page should have all ministries on one page and no pagination
- Ministries in English and French should be sorted correctly.
=> [Bug]: Sorting on Ministries is not implemented 

ckanext/ontario_theme/fanstatic/common.css, ckanext/ontario_theme/templates/external/scheming/package/snippets/additional_info.html, ckanext/ontario_theme/templates/internal/package/snippets/additional_info.html, ckanext/ontario_theme/templates/internal/scheming/package/resource_read.html
- Removes additional info table headers
- Adds description list, terms and definitions for additional information tables
- DATA-1396
- No hidden or visible table headers on additional information tables on dataset and resource page
- Key-value pairs are in `<dt>` and `<dd>` respectively in the additional information table
=> [Task]: Additional info table headers removed and added description lists

config/ckan/ckan.ini
- updates ckan.ini to set `ckan.group_and_organization_list_all_fields_max = 100`
- DATA-1389
- `config/ckan/ckan.ini` is updated
=> [Task]: Update ckan.ini to reflect organization item page limit

ckanext/ontario_theme/fanstatic/common.css, ckanext/ontario_theme/fanstatic/external/ontario_theme.css
Changes design of tabs on Dataset's, Ministry's, Group's and Admin's pages to classic tabs
DATA-1045
- Correct colours when tabs are active, non-active, interactive state
- No gap between tabs and navigation tab line
- Tabs correctly working
- Views match across different devices and match Figma design
=> [Task]: Change tabs to classic tabs including mobile view v2

ckanext/ontario_theme/fanstatic/common.css, ckanext/ontario_theme/fanstatic/scripts/odc-related-datasets-links-feedback.js, ckanext/ontario_theme/fanstatic/scripts/odc-relevant-datasets-form.js, ckanext/ontario_theme/fanstatic/scripts/webassets.yml, ckanext/ontario_theme/templates/internal/package/read_base.html, ckanext/ontario_theme/templates/internal/package/snippets/related_datasets.html, ckanext/ontario_theme/templates/internal/snippets/related_dataset_page.html
- Adds suggested datasets feedback section to the right-hand side of the page when a related dataset link is clicked
- Input fields are available when radio button is selected as "no"
- DATA-1432
- Section looks like figma
- Content is identical to figma content
- Input field is available only when "no" is selected as a radio button
=> [Task]: Adds suggested datasets feedback to the right-hand side of page

ckanext/ontario_theme/templates/internal/package/read.html, ckanext/ontario_theme/templates/internal/package/read_base.html, ckanext/ontario_theme/templates/internal/scheming/package/resource_read.html
- Removes ckan grid system and replaces is with DS grid system on dataset and resource page
- Fixes right hand side boxes error on large screens between 1170px-1199px wide
- DATA-1435
- On screens 1170px-1199px wide, the grey boxes are on the right side of the main content of the dataset and resource pages.
- All content on both types of pages are responsive.
=> [Bug]: Right side boxes are displayed incorrectly on large screens

config/solr/managed-schema
- Tags were of type String in solr, this PR changes tags to be of type "text_case_insensitive", a custom Text field.
- String fields are stored exactly as they are and cannot be modified while Text fields can be modified and can go through lower-casing.
- DATA-871
- Searching terms like "Health" and "health" produce the same results in the same order.
- Requires solr reconfiguring
=> [Task]: Search accuracy - Case insensitivity

ckanext/ontario_theme/datastore.py, ckanext/ontario_theme/plugin.py, ckanext/ontario_theme/templates/internal/package/new_resource_publish.html
Connects the "Run validator to continue" button in the Data Dictionary page to a new page which will contain a review of the metadata and data dictionary fields. At the moment, this page is just a placeholder for the future content. 
This placeholder page will only be rendered when the data dictionary validation completes successfully. If the data dictionary validation fails, the page stays on the Data Dictionary page and the validation error report is shown, as before.
- Test that the workflow from the Data Dictionary page works as expected for 2 cases:
- a csv file with valid data types
- a csv file with a data type error (e.g. string in integer column)
- Make sure that `pkg` variable is passed to the placeholder page (the content of `pkg` should display on the page)
=> Data Validation MVP 1: placeholder page for Step 4 publish

ckanext/ontario_theme/fanstatic/common.css, ckanext/ontario_theme/fanstatic/scripts/odc-step-indicator.js, ckanext/ontario_theme/fanstatic/scripts/webassets.yml, ckanext/ontario_theme/templates/internal/datastore/dictionary.html, ckanext/ontario_theme/templates/internal/package/new_resource_not_draft.html, ckanext/ontario_theme/templates/internal/package/new_resource_publish.html, ckanext/ontario_theme/templates/internal/package/resource_edit_base.html, ckanext/ontario_theme/templates/internal/package/snippets/step_indicator.html, ckanext/ontario_theme/templates/internal/page.html
- Adds step indicator to new resource, data dictionary, and publishing pages
- DATA-1445
- The back button redirect users to the logical previous step
- Step indicator is present on aforementioned workflow pages
=> [Task]: Add Step Indicators to workflow pages

ckanext/ontario_theme/datastore.py, ckanext/ontario_theme/fanstatic/common.css, ckanext/ontario_theme/plugin.py, ckanext/ontario_theme/templates/internal/package/new_resource_publish.html
- The “Edit resource file and metadata” links both redirect back to Step 1: add metadata
- The “Edit data dictionary” link redirects back to Step 2: Add data dictionary
- FR and EN fields are split into two columns
- DATA-1443
- The “Edit resource file and metadata” links both redirect back to Step 1: add metadata
- The “Edit data dictionary” link redirects back to Step 2: Add data dictionary
- FR and EN fields are split into two columns
- The page generally looks like the figma
=> [Task]: Step 4 Content

ckanext/ontario_theme/fanstatic/common.css, ckanext/ontario_theme/plugin.py, ckanext/ontario_theme/templates/internal/snippets/access_level_radio_buttons.html
- Refactored `before_search` to fix issue causing the search-index to not be able to rebuild
- Fixes CSS on ministry and groups pages
- Uses `access_level:*` for the all levels access level radio button
- Search index can be rebuilt without an error
- Can navigate to the homepage without error and dataset counts and lists are accurate (showing datasets from all access levels)
- On dataset page
- by default, the datasets presented are open
- switching between access levels displays the datasets with the corresponding access level
- "Access level" facet grey box is not in the facet list
- facets/filters work as expected
- On ministry/group pages
- in ministry/group list, all dataset counts are correct and show count of datasets from all access levels
- in the ministry/group dataset search …
=> Refactoring `before_search` for radio buttons

ckanext/ontario_theme/templates/internal/package/resource_edit_base.html
- Removes nav tabs from edit resource page
- Adds step indicator to page as step 1
- DATA-1471
- Edit resource page has step indicator step 1
=> [Task]: Edit Resource template header to look like Step 1

ckanext/ontario_theme/datastore.py, ckanext/ontario_theme/plugin.py, ckanext/ontario_theme/resource.py, ckanext/ontario_theme/templates/internal/datastore/dictionary.html, ckanext/ontario_theme/templates/internal/package/resource_validation.html, ckanext/ontario_theme/templates/internal/package/snippets/successful_page_alert.html
- When a non-CSV file is added as a new resource, redirects to Step 2.
- Added new file and blueprint to show validation/upload status as needed.
- Added snippet for successful status page alert.
- Step 2 redirects to data dictionary page with non-CSV files, reworked the data dictionary prepare function
- DATA-1444
- Going through workflow with non-csv files work as expected. (no errors, user goes through all steps and content follow figma)
- Going through workflow with csv files work as expected. (no changes)
=> [Task]: Bypass validation and Data Dictionary form for non-CSV resources

ckanext/ontario_theme/templates/internal/package/snippets/resource_item.html
- Adds accessible name to resource-item-div link on dataset pages
- Removes additional links in resource-item-div, leading to resource page
- DATA-1479
- Resource item div on dataset page has an aria-label
- For non-admin/non-logged in users, the resource-item-div should have only one link (the anchor-div)
- For admin/logged in users, the resource-item-div will have the title, explore button, and edit button as links.
=> [Task]: Add Aria labels to list items on dataset pages

ckanext/ontario_theme/fanstatic/common.css, ckanext/ontario_theme/templates/internal/datastore/snippets/dictionary_form.html, ckanext/ontario_theme/templates/internal/macros/form.html, ckanext/ontario_theme/templates/internal/package/new_resource_publish.html
- Replaces “﻿﻿Field 1. Column Name (text)” with the content in figma
- Removes “Label” field
- Replaces text “Type Override” with “Data type”
- Replaces the blank field in Type Override dropdown with “Select”
- Adds hint text under “Description”
- Updates the Data dictionary content in the publish page
- Adds `macros/form.html` into our repo so we can make changes to the default form components
- Adds hint text to markdown macro.
- DATA-1493
- Content matches Figma and content outlined in ticket
=> [Task]: Modify Data Dictionary page content

ckanext/ontario_theme/fanstatic/common.css, ckanext/ontario_theme/templates/internal/package/snippets/resource_item.html
- Fixes alignment in admin resource list
- Adds padding to top of ul
- DATA-1506 & DATA-1505
- Alignment in admin resource list is fixed
- Hover on first resource does not overlap buttons
=> [Bug]: Fix alignment in admin resource list

ckanext/ontario_theme/fanstatic/common.css, ckanext/ontario_theme/templates/internal/package/snippets/package_base_breadcrumb.html, ckanext/ontario_theme/templates/internal/scheming/package/resource_read.html
- Adds `overflow-wrap: break-word` to the resource page titles
- Adds `word-break: break-all` to the resource page titles with URLs as the titles on mobile
- Replace instance of `word-wrap: break-word` as it is deprecated
- Removed truncation on breadcrumbs on resource page
- DATA-1507
- Resource with URL titles do not overflow horizontally on mobile
- On medium and large screens do not overlap with the side boxes
- No truncation on resource page breadcrumbs
=> [Bug]: Resources with URL titles overlap with side boxes

ckanext/ontario_theme/templates/internal/organization/bulk_process.html, ckanext/ontario_theme/templates/internal/snippets/search_form.html
The `h.add_url_param()` function requires a dictionary with 3 elements: `id`, `group_type`, and `is_organization`. This PR adds those parameters in to the empty `extras` object which was causing an error when rendering the Datasets page from the admin panel of the Ministry page.
1. Go to Ministries page and pick a ministry
2. click the Edit button
3. click the Datasets tab. Verify that the page displays.
=> bugfix: add extras dict to url

ckanext/ontario_theme/templates/internal/package/new_resource_not_draft.html, ckanext/ontario_theme/templates/internal/package/resource_edit.html, ckanext/ontario_theme/templates/internal/package/resource_edit_base.html
- Changes the title of Step 1 for new resources and for editing existing resources to be the same. The title should be: "Add or edit data resource" for both pages.
- Consolidates the text of the browser tab such that text starts with "Add or edit" instead of "Add resource" (new resources) or "Edit" (existing resources). The rest of the tab text should remain as before.
Confirm that:
- Step 1 page `h1` title is `Add or edit data resource` both when creating a new resource and when editing an existing resource
- Step 1 browser tab reads `Add or edit - {dataset name} - {ckan site name}` for new resources and `Add or edit - {resource name} - {dataset name} - {ckan site name}` for existing resources
=> Display same Step 1 title for resource adding or editing

ckanext/ontario_theme/templates/internal/datastore/snippets/dictionary_form.html
Removes hint text from data dictionary page under each column that said: "This can only be changed in the data file."
Confirm this text is no longer displayed on the data dictionary page.
=> Remove hint text from data dictionary page

pipeline/azure-pipelines.yml
- stops CI builds for the validation branch
- ckanext_validation_develop is removed from the pipeline file
=> Disable pipeline for ckanext_validation_develop branch

README.rst
The formatting (section titles) of the README.rst file got lost. This PR restores the original formatting.
Confirm that the section styles look good.
=> fix readme formatting

ckanext/ontario_theme/fanstatic/common.css
Modifies css to allow full column title to be displayed in `<input>` element on Data Dictionary page.
- DATA-1613
Test that full column names are displayed in Data Dictionary page, e.g. this file https://data.ontario.ca/dataset/ontario-guaranteed-annual-income-system-benefit-rates/resource/bbf69b48-16a3-47d2-b127-5fca0626008b
=> [Bug] Column names not cutoff on dictionary page

ckanext/ontario_theme/resource.py, ckanext/ontario_theme/resource_upload.py, ckanext/ontario_theme/templates/internal/datastore/dictionary.html, ckanext/ontario_theme/templates/internal/package/new_resource_publish.html, ckanext/ontario_theme/templates/internal/scheming/package/resource_read.html
Reverts to original code where resource format can be manually entered and removes the automatic application of the `WEB` label to remotes where no format is manually specified. 
Notes: 
- remotely-hosted CSV files will be run through the validation process, but the resource page will not show the Download box or the API box. Since the remote host is the most up-to-date, the catalogue database could potentially diverge significantly from it. 
- the content for the Data Dictionary page created for the case of remote CSV files has been removed, since the validation process is no longer being skipped for remote CSVs.
- manually entered formats that contain a typo (e.g. CVS) or are not in the accepted format list (e.g. MYFORMAT) will not be checked or corrected and will pass as is.
DATA-1630 …
=> [Task] Allow formats for remotes to be changed manually

ckanext/ontario_theme/resource.py
Removes a check for `validation_status` in the `resource` object which prevents pre-validation resources from being updated.
Needs to work for all cases (pre-validation resources, post-validation resources, new resources).
=> rm check for validation_status in resource

ckanext/ontario_theme/datastore.py
Resolves the 500 server error when the data dictionary form is left completely blank by redirecting to publish page after Step 3. 
Also takes care of case when the data type field not filled in but the description field is added. In this case, the modified data dictionary needs to be pushed to database, same as when the data type is defined.
DATA-1678
Test
- creating a new resource without filling out the data dictionary form redirects to publish page without error
- creating a new resource and filling out description field only (leaving data type untouched) in data dictionary form redirects to publish page without error and the description is listed in the publish page
- creating or editing a resource with data dictionary form filled out works as normal
Also test that
=> Redirect to publish page when dictionary form left blank
