ckanext/ontario_theme/templates/base.html
Enable some more basic analytics for the site.
=> Task: Add GA script.

ckanext/ontario_theme/plugin.py, ckanext/ontario_theme/templates/header.html, ckanext/ontario_theme/templates/home/help.html
Added help page using flask blueprints instead
of pylons action/controller routing.
=> Task: Add help page.

ckanext/ontario_theme/templates/home/help.html, ckanext/ontario_theme/templates/home/snippets/ontario_theme_contact_us.html
Added twitter to contact us section of home page.
Added data inventory link to help page as it seemed
to fit content-wise with other info there. Also added a
little blurb about the data directive to an existing
link/paragraph.
=> Task: Add twitter and data inventory links.

ckanext/ontario_theme/fanstatic/cards.less, ckanext/ontario_theme/fanstatic/ontario_theme.css, ckanext/ontario_theme/templates/home/snippets/ontario_theme_featured_content.html
Image was no longer loading / available.
=> Bug: Replace 3rd party image.

ckanext/ontario_theme/plugin.py, ckanext/ontario_theme/tests/test_plugin.py
Setup test to use localhost machine.
=> Bug: Remove hardcoded dev url.

ckanext/ontario_theme/tests/test_plugin.py
This is part of debuging and setting up CI testing.
=> Bug: Get erroring test to pass.

Jenkinsfile, ckanext/ontario_theme/plugin.py, ckanext/ontario_theme/tests/test_helpers.py, ckanext/ontario_theme/tests/test_plugin.py, setup.py
This is a rough pipeline to test this extension.
This pipeline effectively builds a CKAN 2.8.2 instance,
moves the extension's code into the proper spot, prepares it
for tests and runs the tests.
=> Task: Add Jenkinsfile for new pipeline for CI.

ckanext/ontario_theme/templates/home/snippets/ontario_theme_featured_content.html
=> add "get featured" blurb below feature banner

ckanext/ontario_theme/ontario_theme_dataset.json, ckanext/ontario_theme/templates/scheming/package/snippets/resource_form.html, ckanext/ontario_theme/tests/test_create_dataset.py, ckanext/ontario_theme/tests/test_resource_upload.py, ckanext/ontario_theme/tests/test_update_dataset.py
This commit consists of 1 large change, changing the schema using ontario_theme_dataset.json to reflect desired fields. The changes to the schema are also reflected in 3 test files.
=> Task: update schema

ckanext/ontario_theme/fanstatic/cards.less, ckanext/ontario_theme/fanstatic/colours.less, ckanext/ontario_theme/fanstatic/ontario_theme.css
This PR consists of one change, changing the card class background colour to match the card background color of ontario.ca. This colour is stored in the colours.less file.
=> Odc beta ontarioca styled cards

ckanext/ontario_theme/templates/home/snippets/ontario_theme_featured_content.html
This PR consists of one change, the addition of a medium blog article link for the landing page.
=> Task: Inclusion on medium article link.

ckanext/ontario_theme/fanstatic/header.less, ckanext/ontario_theme/fanstatic/ontario_theme.css
Logo needed more whitespace around top and bottom.
It also needed to have size reduced.
Also, left align site name to main logo.
=> Improvement: Fix spacing around logo.

ckanext/ontario_theme/ontario_theme_dataset.json, ckanext/ontario_theme/templates/package/snippets/resource_item.html
This PR consists of one commit for one change: Data_last_updated field for a resource added to the schema and to the dataset display page.
=> Task: Add data last updated.

ckanext/ontario_theme/fanstatic/ontario_theme.css, ckanext/ontario_theme/fanstatic/ontario_theme.less, ckanext/ontario_theme/templates/group/edit.html, ckanext/ontario_theme/templates/group/edit_base.html, ckanext/ontario_theme/templates/group/index.html, ckanext/ontario_theme/templates/group/read_base.html, ckanext/ontario_theme/templates/organization/edit_base.html, ckanext/ontario_theme/templates/organization/read_base.html
This PR harmonizes the styles among pages for packages, organizations, groups. It consists of 7 commits for the following changes:
- changing "Manage" to "Edit" on the view organization and view group pages
- extending search styles to groups search
=> Extend style adjustments

ckanext/ontario_theme/templates/scheming/package/read.html
The wrong default email was used for the catalogue. There is one commit to change one string.
=> Bug: Wrong default email for dataset contacts.

ckanext/ontario_theme/i18n/fr/LC_MESSAGES/ckanext-ontario_theme.po, ckanext/ontario_theme/templates/home/snippets/ontario_theme_intro.html
=> Improvement: Fix download link for GA purposes.

ckanext/ontario_theme/licences.json, ckanext/ontario_theme/plugin.py, ckanext/ontario_theme/templates/snippets/facet_list.html, ckanext/ontario_theme/templates/snippets/license.html
Licences must be displayed in french as well as english. This PR consists of one commit to make licences bilingual and make the template changes in dataset search and dataset display.
=> Bug: Missing french licences labels.

ckanext/ontario_theme/ontario_theme_dataset.json
This PR consists of one commit for one change:
* add a new update frequency for once every 5 years
Statscan datasets have a 5 year updated frequency. These records now exist in the catalogue.
=> Task: Add 5 year update frequency.

ckanext/ontario_theme/licences.json
This PR consists of one commit to make one change: 
* Add StatsCan Open Licence to licences
=> Task: Add StatsCan Open Licence to licences.

ckanext/ontario_theme/fanstatic/alerts.less, ckanext/ontario_theme/fanstatic/ontario_theme.css, ckanext/ontario_theme/i18n/ckanext-ontario_theme.pot, ckanext/ontario_theme/i18n/fr/LC_MESSAGES/ckanext-ontario_theme.po, ckanext/ontario_theme/templates/header.html
This PR consists of one commit to make one change. Survey banner was added globally to site. Banner mirrors the one from the previous catalogue.
=> Task: Add survey banner globally to site.

ckanext/ontario_theme/templates/user/read_base.html
This PR consists of 2 commits to remove the number of followers and the followers button on a user page.
=> Odc beta remove follow feature

ckanext/ontario_theme/templates/group/snippets/info.html, ckanext/ontario_theme/templates/package/read_base.html, ckanext/ontario_theme/templates/snippets/organization.html, ckanext/ontario_theme/templates/user/read_base.html
This PR consists of 8 commits to remove the follow feature from user, group, organization, and package pages.
This PR cherry picks from Pull Requests #116 and #119 and applies them to master (instead of the odc-beta branch).
=> Remove follow feature

ckanext/ontario_theme/resource_upload.py, ckanext/ontario_theme/schemas/internal/ontario_theme_dataset.json, ckanext/ontario_theme/templates/internal/home/snippets/ontario_theme_featured_content.html
- Compare resource formats in same case.
- Apply license_id field_name update.
- Update image path.
=> Bug: Fix a few bugs.

ckanext/ontario_theme/schemas/licences.json
Add Crown Land use Policy Atlas Terms of Use to list of licences.
=> Task: Add Crown Land Use Policy Atlas Terms of Use.

ckanext/ontario_theme/schemas/licences.json
This PR consists of one commit to make one change: add Apache LIcense 2.0 to the list of licences.
=> Task: Add Apache License 2.0 to licences.

ckanext/ontario_theme/fanstatic/external/ontario_theme.css, ckanext/ontario_theme/fanstatic/internal/general_styles.less, ckanext/ontario_theme/fanstatic/internal/ontario_theme.css, ckanext/ontario_theme/plugin.py, ckanext/ontario_theme/schemas/ontario_theme_organization.json, ckanext/ontario_theme/templates/internal/group/read.html, ckanext/ontario_theme/templates/internal/organization/read.html, ckanext/ontario_theme/templates/internal/package/search.html, ckanext/ontario_theme/templates/internal/snippets/facet_list.html, ckanext/ontario_theme/templates/internal/snippets/ontario_theme_category_facet.html, ckanext/ontario_theme/templates/internal/snippets/ontario_theme_jurisdiction_facet.html, ckanext/ontario_theme/templates/internal/snippets/package_item.html
Add new fields to Organization to help identify it more easily and it's assigned datasets.
Organization Jurisdiction will help in future federation efforts and category will help distinguish the types/level of organization within the jurisdiction.
A jurisdiction and category should be combined to create a single organization (e.g. _Canada (Federal Ministry)_ or an ontario agency could be _Agency Name (Provincial Agency)_.  All datasets for these organizations can be assigned to them. These fields are displayed on the UI to help users quickly identify where the data comes from.  These fields are also indexed to help faceting against them.
=> Task: Allow identifying agencies and their datasets.

ckanext/ontario_theme/controller.py, ckanext/ontario_theme/plugin.py, ckanext/ontario_theme/templates/internal/package/new_package_form.html
This PR consists of 4 commits to make one feature change: allow users to skip adding resources when creating a new package, When creating a new package, users should now see the addition of a new submit button: "Save and finish".
=> Submit package without resource

ckanext/ontario_theme/i18n/fr/LC_MESSAGES/ckanext-ontario_theme.po, ckanext/ontario_theme/schemas/ontario_theme_organization.json, ckanext/ontario_theme/templates/external/scheming/package/read.html, ckanext/ontario_theme/templates/internal/scheming/organization/about.html
- added org_contact to organization schema
- updated dataset to pull organization contact if maintainer is not specified
- updated translations
=> Task: Added organization contact and associated it with datasets

ckanext/ontario_theme/i18n/fr/LC_MESSAGES/ckanext-ontario_theme.po, ckanext/ontario_theme/plugin.py, ckanext/ontario_theme/schemas/external/ontario_theme_dataset.json, ckanext/ontario_theme/schemas/internal/ontario_theme_dataset.json
- added asset type to the search facets
- added translation
- fixed translation issue for access level
=> Task: Add asset type as a search facet

ckanext/ontario_theme/fanstatic/external/ontario_theme.css, ckanext/ontario_theme/fanstatic/internal/ontario_theme.css
CSS files were touched manually. This repairs the css files.
=> Bug: Repair less-generated css files.

ckanext/ontario_theme/fanstatic/internal/msappproxy.js, ckanext/ontario_theme/templates/internal/base.html
Proxy Colby has absolute paths from non proxy Colby that don't work. this is a fix to replace them.
=> Task: Fix for absolute paths for proxy colby.

ckanext/ontario_theme/schemas/external/ontario_theme_dataset.json, ckanext/ontario_theme/schemas/internal/ontario_theme_dataset.json
=> Task: make resource name field fluent-y

ckanext/ontario_theme/fanstatic/external/ontario_theme.css, ckanext/ontario_theme/fanstatic/internal/general_styles.less, ckanext/ontario_theme/fanstatic/internal/labels.less, ckanext/ontario_theme/fanstatic/internal/ontario_theme.css, ckanext/ontario_theme/templates/internal/package/snippets/resource_item.html
- changed previous format icon styles to formatted text labels with the resource format name
- any format longer than 4 characters will default to "other"
=>  Task: Make format icons accessible

ckanext/ontario_theme/i18n/fr/LC_MESSAGES/ckanext-ontario_theme.po, ckanext/ontario_theme/plugin.py, ckanext/ontario_theme/templates/internal/package/snippets/resources_list.html
- shorten 01-01-YYYY - 12-31-YYYZ display to YYYY - YYYZ
- shorten 04-01-YYYY - 03-31-YYYZ display to Fiscal YYYY - YYYZ
- removed "Covers.." text
=> Task: User friend date range display

ckanext/ontario_theme/schemas/ontario_theme_organization.json
Revert back to ckanext-scheming's organization_upload snippet to repair image upload issues.
=> Bug: ontario_theme_organization_upload snippet throws error.

ckanext/ontario_theme/schemas/ontario_theme_organization.json, ckanext/ontario_theme/templates/internal/scheming/form_snippets/ontario_theme_organization_upload.html
Wrapping the image_upload form input in a div with the form-group class seems to disable image uploads.
=> Bug: form-group class disables image_upload form input.

ckanext/ontario_theme/templates/internal/package/snippets/ontario_theme_access_level.html, ckanext/ontario_theme/templates/internal/package/snippets/resources_list.html
- added banner for harvested datasets from EDC, banner includes:
- link to source record
- dataset access level information
- data availability
=> #Task clarify COLBY data status

README.rst
* add _Directory Structure_ section to README.rst
=> Update README to detail directory structure

scripts/ckan_install.sh
Fixes a couple of typos in the ckan install script where admin account is set up
=> fixes ckan script typos in admin account setup

README.rst, setup.py
Updates [setup.py](https://github.com/ongov/ckanext-ontario_theme/blob/ckan_2.9_ver/setup.py) to include:
- correct python version (3.8)
- current contact info
Updates CKAN version to 2.9.x in [README](https://github.com/ongov/ckanext-ontario_theme/blob/ckan_2.9_ver/README.rst)
- confirm that contact info is correct
=> update version and contact info in setup.py

setup.py
upgrade version to v1.3.0 in setup.py
Release 1.3.0 includes the following features:
* Update breadcrumb styling to match Ontario Design System
* Ontario Forest Region geo breakdown
* Fix for translation bug for license in resource table
=> Release v1.3.0

ckanext/ontario_theme/schemas/external/ontario_theme_dataset.json, ckanext/ontario_theme/schemas/internal/ontario_theme_dataset.json
MNRF requested 'Ontario Forest Region' be added to the list of possible 'Geography Breakdowns'.
=> added Ontario Forest Region to Geographic Breakdown choices

ckanext/ontario_theme/fanstatic/common.css, ckanext/ontario_theme/fanstatic/external/ontario_theme.css, ckanext/ontario_theme/templates/internal/home/snippets/ontario_theme_categories.html
- Adds Design System link styling
- Updates homepage links
- Underlines dataset links on hover
- Underlines keywords on hover
- Adds focus state to all links
- Adds nonbreakable space to keywords
- Underlines survey links
- Focus state appears in each link
- Keyword links redirect to correct location
- All links are underlined at least on hover
=> Ckan 2.9 align links to Design System

ckanext/ontario_theme/resource_upload.py
Same as #273 but for the CKAN 2.8 branch.
Code change is same.
=> CKAN2.8 FIX: allows uploads of zip files containing folders

setup.py
upgrade version to v1.3.1 in setup.py
Release 1.3.1 includes the following fixes:
* Allow uploads of zip files containing folders (#274)
=> Release v1.3.1

setup.py
upgrade version to v2.0.0 in setup.py
Release v2.0.0 includes the following features:
* Major UI overhaul
* upgrade to CKAN 2.9.7
* Ontario Design System compliance
=> Release v2.0.0

setup.py
Release v2.1.0 includes the following features:
* linting tools and formatted code #328 #322
* UI improvements and bug fixes #323 #324 #326 #325 #332
* Translation fixes #331
=> Upgrade version to v2.1.0 in setup.py

ckanext/ontario_theme/fanstatic/common.css, ckanext/ontario_theme/templates/internal/package/snippets/resource_item.html
- Aligns icon with text in button
- Icon and text are aligned horizontally
=> Dataset resource buttons bug

setup.py
Release v2.1.1 includes the following features:
* Code and Documentation cleanup #340, #337
* UI improvements and translation fixes #336, #338, #339, #341, #343, #345, #344
* Logout button fix #347
=> upgrade version to v2.1.1 in setup.py

setup.py
Release v2.1.2 includes the following features:
- content fixes (#361 , #356 , #354 , #351, #346 )
- UI improvements for mobile (#355)
- logout button returns to correct page (#350)
=> Release 2.1.2

.gitignore, .vscode/extensions.json, .vscode/settings.json.default
- Standardizes a list of VSCode extensions that will make the code base easier to use and understand for the developers.
- Adds necessary workspace settings so the extensions work as expected. 
- Upon pulling branch into local in VSCode, a pop up on the bottom right of screen appears, with options to either install all extensions or show recommendations.
- After installing the extensions,
- HTML files are fully syntax highlighted, including jinja snippets
- GitLens works on every line
- Python scripts have their errors and warnings marked on the code
- NGINX works on .conf files and specified Nginx configuration files.
- Meld Diff works
=> List of recommended VSCode extensions

scripts/setup_ckan_local.sh
* fixes issues caused by merging of #226 into main with branching
* fix branch switch to non-existent branch when setting up local ontario_theme
* local script setup works when working directly from main branch
=> Fix branch switch with local ontario_theme setup

setup.py
upgrade version to v2.1.5 in setup.py
Release v2.1.5 includes the following features:
* UI improvements and Ontario Design System compliance #369 #379 #381 #387
* Fix broken links #317
* Filetype GeoJSON format display and error fixes #386 #380
* Formatting and Dev tools #382 #383 
* Local setup scripts and README updates #226 #388
=> Release v2.1.5

ckanext/ontario_theme/fanstatic/internal/ontario_theme.css, ckanext/ontario_theme/templates/internal/base.html, ckanext/ontario_theme/templates/internal/header.html
- develops site-wide banner for COLBY
=> Ckan 2.8 colby banner

setup.py
upgrade version to v2.1.6 in setup.py
Release v2.1.6 includes the following features:
* UI fixes for overlapping objects #395 #394
* Remove logging errors and deprecated methods #393
* Fix `Additional Information` dates format #391
=> update setup.py to v2.1.6

setup.py
upgrade version to v2.1.7 in setup.py
Release v2.1.7 includes the following features:
* Add data types in CKAN's data dictionary #390
* UI improvements #400
=> update setup.py to v2.1.7

config/solr/lang/contractions_fr.txt, config/solr/lang/stopwords_fr.txt, config/solr/protwords.txt, config/solr/solrconfig.xml, config/solr/stopwords.txt, config/solr/synonyms.txt, scripts/setup_solr.sh
**Pull Request: Update CKAN Core & SOLR8 Integration Fixes**
1. **CKAN Core & SOLR8 Integration**:
- Addressed critical issues regarding CKAN core not updating in tandem with changes pushed to SOLR8.
- Steps accomplished:
1. Stopping the solr8 server.
2. Removing all temporary files.
3. Creating new configuration directories.
4. Copying configuration files, including `managed-schema`, `solrconfig.xml`, `protwords.txt`, `stopwords.txt`, and `synonyms.txt`, from the ckan ontario-theme to the appropriate directories.
5. Restarting the Solr8 server.
6. Creating CKAN core.
- Additionally, specific fixes have been applied to the `synonyms.txt` and `protwords.txt` files.
2. **Testing & Replacement of Files**:
- Instructions have been provided to ensure that any changes made can be tested and …
=> fixed scripts w/solr8 ckan core

setup.py
upgrade version to v2.1.8 in setup.py
Release v2.1.8 includes the following features:
* UI fixes and updates #407, #405, #404, #403, #402
* AI content #410, #406, #408
* Meta tags for better SEO #409
* solr8 script fixes #397
=> Release v2.1.8

ckanext/ontario_theme/templates/internal/home/layout3.html
Reverts the change to replace ODC Feedback Banner to AI Survey Recruitment Banner 
AI Survey Recruitment banner is not visible
=> Change back homepage banner to 'contact us'

setup.py
upgrade version to v2.1.9 in setup.py
Release v2.1.9 includes the following features:
* Accessbility Fixes #414
* Help Page changes #417
* Header Changes for Internal Data Catalogue #424
* Other UI fixes #423, #420, #419, #418, #415, #413, #412
=> release v2.1.9

setup.py
Prod Release v2.1.9 includes the following features:
* Accessibility Fixes #414
* Help Page changes #417 
* Header Changes for Internal Data Catalogue #424
* Other UI fixes #423, #420, #419, #418, #415, #413, #412
=> Prod Release v2.1.9

setup.py
upgrade version to v2.1.10 in setup.py
Release v2.1.10 includes the following features:
*UI Changes on Groups, Ministries, Dataset and Resource pages #438 #437 #435 #434 #433 #431 
*Pagination UX improvements #436 #432
=> release v2.1.10

setup.py
upgrade version to v2.1.11 in setup.py
Release v2.1.11 includes the following features:
*UI enhancements #439 #442 #443
=> release_v2.1.11

scripts/README.md
- Update to instructions specific to an M1
- Links to troubleshooting threads
-  Checking if "Known Issues" section is clear
=> [Task] Update to README.md

setup.py
upgrade version to release_v2.1.12 in setup.py
Release v2.1.12 includes the following features:
* SEO improvement to use ld+json #455 #466
* Search improvements #464
* UI Changes and Fixes #456 #458 #459 #468 #463 #462
* Accessibility improvements #461
=> release_v2.1.12

ckanext/ontario_theme/fanstatic/common.css, ckanext/ontario_theme/plugin.py, ckanext/ontario_theme/schemas/external/ontario_theme_dataset.json, ckanext/ontario_theme/templates/external/scheming/package/snippets/additional_info.html, ckanext/ontario_theme/templates/internal/package/snippets/additional_info.html, ckanext/ontario_theme/templates/internal/scheming/package/resource_read.html, ckanext/ontario_theme/validators.py
Reverts ongov/ckanext-ontario_theme#475
=> Revert "Test PR"

ckanext/ontario_theme/fanstatic/common.css, ckanext/ontario_theme/plugin.py, ckanext/ontario_theme/schemas/external/ontario_theme_dataset.json, ckanext/ontario_theme/templates/external/scheming/package/snippets/additional_info.html, ckanext/ontario_theme/templates/internal/package/snippets/additional_info.html, ckanext/ontario_theme/templates/internal/scheming/package/resource_read.html, ckanext/ontario_theme/validators.py
Merge 2 commits:
```
commit 2f93540739d63a4b29de4547f4202700bbeb1654 (HEAD -> main_reset, origin/develop, develop)
Author: AleexGreen <alex.green@ontario.ca>
Date:   Fri Jan 12 11:12:24 2024 -0500
validator for stripping fluent values (#473)
commit d2d3a58ee9a148bdab0faa86290f91f8c022b070 (workflow_redesign)
Author: AleexGreen <alex.green@ontario.ca>
Date:   Mon Jan 8 14:50:17 2024 -0500
[Task]: change Addtional Information table from <table> to <div>s (#467)
* Additional info table on dataset page switched to grid
* Resource page additional info table + switching to ds grid
```
=> Merge 2 commits from develop

ckanext/ontario_theme/plugin.py
Removed duplicate import statement for datetime
DATA-263
No 500 error on dataset pages that have data
=> [Hotfix]: Dataset 500 error

ckanext/ontario_theme/plugin.py
Removed duplicate import statement for datetime
DATA-236
No 500 error on dataset pages that have data
=> hotfix for dataset 500 error

setup.py
upgrade version to v2.1.13 in setup.py
Release v2.1.13 includes the following features:
* Fix datetime import duplication causing 500 error
=> Release v2.1.13

ckanext/ontario_theme/plugin.py, setup.py
Release v2.1.13 includes the following features:
* Fix datetime import duplication causing 500 error
=> Release 2.1.13

setup.py
upgrade version to v2.1.14 in setup.py
Release v2.1.14 includes the following features:
* Improve Ministries page by removing page #493
* Simplify logs #492
* UI improvements #490 #491
=> release v2.1.14

.gitignore, ckanext/ontario_theme/templates/internal/gtm.html, ckanext/ontario_theme/templates/internal/gtm_ns.html, pipeline/azure-pipelines.yml, setup.py
- enables both pipelines and MANIFEST file changes in the same code base
- DATA-1208
- all files needed for pipeline are in branch `manifest_file`
=> Merge pipelines and MANIFEST file changes

.gitignore, MANIFEST.in, ckanext/ontario_theme/templates/internal/gtm.html, ckanext/ontario_theme/templates/internal/gtm_ns.html, pipeline/azure-pipelines.yml, setup.py
- MANIFEST.in file changes to add missing files types and directories for build
- add GA files to template/internal and remove them from gitignore
- DATA-1208
- Wheel package creation and deployment is successful
=> [Task] Update MANIFEST file to enable whl pkg creation

pipeline/azure-pipelines.yml
- add 'v' to tags in pipeline
- DATA-1425
- tags are now with a 'v', and all subsequent PRs are successfully deployed on merge into develop
=> [Task] Add 'v' to tags in pipeline

pipeline/azure-pipelines.yml
- Force artifact push even if it exists
- DATA-1425
- artifacts are always pushed
=> [Task] Artifact gets skipped if already exist

pipeline/azure-pipelines.yml, setup.py
- Change artifact location
- DATA-1425
- artifact pushed to new location
=> [Task] Change artifact location

ckanext/ontario_theme/fanstatic/common.css, ckanext/ontario_theme/templates/internal/package/read.html, ckanext/ontario_theme/templates/internal/package/snippets/related_datasets.html
- Adds related datasets section between the two feedback callouts
- Adds beta tag beside the heading
- Adds input field and radio buttons to section
- Adds submit button to section
- DATA-1431
- Section looks like figma
- Content is identical to figma content
=> [Task]: Add section to display list of related datasets

ckanext/ontario_theme/fanstatic/common.css, ckanext/ontario_theme/plugin.py, ckanext/ontario_theme/schemas/hackathon/test_data.json, ckanext/ontario_theme/templates/internal/package/read.html, ckanext/ontario_theme/templates/internal/package/snippets/related_datasets.html, ckanext/ontario_theme/templates/internal/snippets/related_datasets_viz.html
- Add test data and test data viz embedding to related datasets section
-DATA-1433
- visualization and related datasets section are both half the width of the page and the visualization looks and works as expected.
=> [Task]: Add data viz embedding to related datasets section

config/gtm/gtm.html, config/gtm/gtm_ns.html
- fix gtm and gtm_ns files
- DATA-1454
- GTM tag is updated
- Analytics are working again
=> [Bug]: Fix GTM file 

ckanext/ontario_theme/fanstatic/common.css, ckanext/ontario_theme/templates/internal/package/read.html, ckanext/ontario_theme/templates/internal/package/read_base.html, ckanext/ontario_theme/templates/internal/scheming/package/resource_read.html, config/solr/managed-schema, pipeline/azure-pipelines.yml, setup.py
- Release v2.1.30 to main
- UI updates #515 #523 #524
- Search Accuracy #516
- Pipeline improvements
- n/a
=> Release v2.1.30

pipeline/azure-pipelines.yml
***NO_CI***
- Update pipeline refs to main
- Pipeline should refer to main when in main branch
- refs updated to main from develop
=> [Hotfix] Change pipeline refs to main

ckanext/ontario_theme/plugin.py
Removes duplicated fn in `plugin.py`
Verify removal.
=> rm dupe fn

pipeline/azure-pipelines.yml, setup.py
The status code was returned as "3". Have fixed this issue using workaround as this is bug with systemctl/supervisor .
Azure Devops pipeline file, Deployment stage for each env (IST/UAT/PRD)
=> Data 1504 - Fix issue with pipeline with cleaning up cache

ckanext/ontario_theme/page.py, ckanext/ontario_theme/templates/internal/snippets/search_form.html
- Removes ARIA errors on dataset search page, about page, and the ministries and group page
- DATA-1539
- Using ARC toolkit, make sure there are no errors on the dataset search page, about page, ministries page and groups page.
=> [Task]: Conduct ARIA labelling review

.vscode/extensions.json, README.rst
- Updates documentation with pre-commit manual steps
- removes Meld and add Diff (fabiospampinato.vscode-diff) instead to VSCode Extensions
- Adds documentation for VSCode extensions
- DATA-1178
- Documentation is accurate
=> [Task]: Update documentation with manual git commit instructions

pipeline/azure-pipelines.yml
- use system branch value rather than hardcoding it
- DATA-1561
- pipelines are working as intended
=> [Task]: Unify pipeline develop and main config

ckanext/ontario_theme/templates/internal/gtm.html, ckanext/ontario_theme/templates/internal/gtm_ns.html, ckanext/ontario_theme/templates/internal/gtm_pageview.html, ckanext/ontario_theme/templates/internal/page.html, config/gtm/gtm.html, config/gtm/gtm_ns.html
Updates GA snippets and excludes specific paths from being tracked by GA.
Review logic of the path matching. Only those paths that are not to be excluded should be passed to GA. 
Review that logic works for paths in test (current state) and test.data4 (state with validation feature).
=> Update GA snippets and exclude specific paths from tracking

ckanext/ontario_theme/templates/internal/gtm.html, ckanext/ontario_theme/templates/internal/gtm_ns.html, ckanext/ontario_theme/templates/internal/gtm_pageview.html, ckanext/ontario_theme/templates/internal/page.html, config/gtm/gtm.html, config/gtm/gtm_ns.html, setup.py
- Redoing PR #607 because of pipeline issues
- Updates GA snippets and excludes specific paths from being tracked by GA.
- DATA-1585
- Review logic of the path matching. Only those paths that are not to be excluded should be passed to GA. 
- Review that logic works for paths in test (current state) and test.data4 (state with validation feature).
=> [Task]: Update GA snippets and exclude specific paths from tracking

ckanext/ontario_theme/templates/internal/package/snippets/schema_markup.html
- Add `temporal` which holds the 'Last Validated Date' to the dataset schema
- DATA-1567
- schema is valid and temporal value is populated
=> [Task] Add Last Validated Date to the dataset schema

scripts/setup_ckan_local.sh, scripts/setup_solr.sh
- Fixes local setup script
- DATA-1593
- local install is successful
- scheming, solr and nginx does not have version issues.
=> [Task] Fix local scripts

setup.py
- Manually update major version due to bug in CI
- version is 3.0.0 and get bumped to version and tag 3.0.1 after merge.
=> [Task] Update major version number for Data Validation release
